// qgl_sdl.c -- qgl function-pointer table for the SDL3 port.
//
// Entry points are resolved by dlopen'ing Apple's OpenGL framework
// directly instead of using SDL_GL_GetProcAddress: SDL cannot resolve GL
// functions until an SDL_WINDOW_OPENGL window has been created, but the
// renderer calls QGL_Init before GLimp_SetMode creates the window.
// dlopen'ing the framework is order-independent. The framework handle is
// process-lifetime (never dlclose'd) so the qgl pointers stay valid
// across vid_restart cycles.
//
// Replaces linux/qgl_linux.c (which assigned compile-time-linked libGL
// symbols). The log/dll wrapper layers are dropped: qgl* point straight at
// the driver entry points; unavailable extensions stay NULL and the
// renderer null-checks them.

#include <dlfcn.h>

#include "ref_gl/gl_local.h"

/* Global qgl* pointer definitions -- copied verbatim from
 * linux/qgl_linux.c lines 16-361. */
void ( APIENTRY * qglAccum )(GLenum op, GLfloat value);
void ( APIENTRY * qglAlphaFunc )(GLenum func, GLclampf ref);
GLboolean ( APIENTRY * qglAreTexturesResident )(GLsizei n, const GLuint *textures, GLboolean *residences);
void ( APIENTRY * qglArrayElement )(GLint i);
void ( APIENTRY * qglBegin )(GLenum mode);
void ( APIENTRY * qglBindTexture )(GLenum target, GLuint texture);
void ( APIENTRY * qglBitmap )(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void ( APIENTRY * qglBlendFunc )(GLenum sfactor, GLenum dfactor);
void ( APIENTRY * qglCallList )(GLuint list);
void ( APIENTRY * qglCallLists )(GLsizei n, GLenum type, const GLvoid *lists);
void ( APIENTRY * qglClear )(GLbitfield mask);
void ( APIENTRY * qglClearAccum )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglClearColor )(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void ( APIENTRY * qglClearDepth )(GLclampd depth);
void ( APIENTRY * qglClearIndex )(GLfloat c);
void ( APIENTRY * qglClearStencil )(GLint s);
void ( APIENTRY * qglClipPlane )(GLenum plane, const GLdouble *equation);
void ( APIENTRY * qglColor3b )(GLbyte red, GLbyte green, GLbyte blue);
void ( APIENTRY * qglColor3bv )(const GLbyte *v);
void ( APIENTRY * qglColor3d )(GLdouble red, GLdouble green, GLdouble blue);
void ( APIENTRY * qglColor3dv )(const GLdouble *v);
void ( APIENTRY * qglColor3f )(GLfloat red, GLfloat green, GLfloat blue);
void ( APIENTRY * qglColor3fv )(const GLfloat *v);
void ( APIENTRY * qglColor3i )(GLint red, GLint green, GLint blue);
void ( APIENTRY * qglColor3iv )(const GLint *v);
void ( APIENTRY * qglColor3s )(GLshort red, GLshort green, GLshort blue);
void ( APIENTRY * qglColor3sv )(const GLshort *v);
void ( APIENTRY * qglColor3ub )(GLubyte red, GLubyte green, GLubyte blue);
void ( APIENTRY * qglColor3ubv )(const GLubyte *v);
void ( APIENTRY * qglColor3ui )(GLuint red, GLuint green, GLuint blue);
void ( APIENTRY * qglColor3uiv )(const GLuint *v);
void ( APIENTRY * qglColor3us )(GLushort red, GLushort green, GLushort blue);
void ( APIENTRY * qglColor3usv )(const GLushort *v);
void ( APIENTRY * qglColor4b )(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void ( APIENTRY * qglColor4bv )(const GLbyte *v);
void ( APIENTRY * qglColor4d )(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void ( APIENTRY * qglColor4dv )(const GLdouble *v);
void ( APIENTRY * qglColor4f )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglColor4fv )(const GLfloat *v);
void ( APIENTRY * qglColor4i )(GLint red, GLint green, GLint blue, GLint alpha);
void ( APIENTRY * qglColor4iv )(const GLint *v);
void ( APIENTRY * qglColor4s )(GLshort red, GLshort green, GLshort blue, GLshort alpha);
void ( APIENTRY * qglColor4sv )(const GLshort *v);
void ( APIENTRY * qglColor4ub )(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void ( APIENTRY * qglColor4ubv )(const GLubyte *v);
void ( APIENTRY * qglColor4ui )(GLuint red, GLuint green, GLuint blue, GLuint alpha);
void ( APIENTRY * qglColor4uiv )(const GLuint *v);
void ( APIENTRY * qglColor4us )(GLushort red, GLushort green, GLushort blue, GLushort alpha);
void ( APIENTRY * qglColor4usv )(const GLushort *v);
void ( APIENTRY * qglColorMask )(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void ( APIENTRY * qglColorMaterial )(GLenum face, GLenum mode);
void ( APIENTRY * qglColorPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglCopyPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void ( APIENTRY * qglCopyTexImage1D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
void ( APIENTRY * qglCopyTexImage2D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void ( APIENTRY * qglCopyTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void ( APIENTRY * qglCopyTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglCullFace )(GLenum mode);
void ( APIENTRY * qglDeleteLists )(GLuint list, GLsizei range);
void ( APIENTRY * qglDeleteTextures )(GLsizei n, const GLuint *textures);
void ( APIENTRY * qglDepthFunc )(GLenum func);
void ( APIENTRY * qglDepthMask )(GLboolean flag);
void ( APIENTRY * qglDepthRange )(GLclampd zNear, GLclampd zFar);
void ( APIENTRY * qglDisable )(GLenum cap);
void ( APIENTRY * qglDisableClientState )(GLenum array);
void ( APIENTRY * qglDrawArrays )(GLenum mode, GLint first, GLsizei count);
void ( APIENTRY * qglDrawBuffer )(GLenum mode);
void ( APIENTRY * qglDrawElements )(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void ( APIENTRY * qglDrawPixels )(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglEdgeFlag )(GLboolean flag);
void ( APIENTRY * qglEdgeFlagPointer )(GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglEdgeFlagv )(const GLboolean *flag);
void ( APIENTRY * qglEnable )(GLenum cap);
void ( APIENTRY * qglEnableClientState )(GLenum array);
void ( APIENTRY * qglEnd )(void);
void ( APIENTRY * qglEndList )(void);
void ( APIENTRY * qglEvalCoord1d )(GLdouble u);
void ( APIENTRY * qglEvalCoord1dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord1f )(GLfloat u);
void ( APIENTRY * qglEvalCoord1fv )(const GLfloat *u);
void ( APIENTRY * qglEvalCoord2d )(GLdouble u, GLdouble v);
void ( APIENTRY * qglEvalCoord2dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord2f )(GLfloat u, GLfloat v);
void ( APIENTRY * qglEvalCoord2fv )(const GLfloat *u);
void ( APIENTRY * qglEvalMesh1 )(GLenum mode, GLint i1, GLint i2);
void ( APIENTRY * qglEvalMesh2 )(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void ( APIENTRY * qglEvalPoint1 )(GLint i);
void ( APIENTRY * qglEvalPoint2 )(GLint i, GLint j);
void ( APIENTRY * qglFeedbackBuffer )(GLsizei size, GLenum type, GLfloat *buffer);
void ( APIENTRY * qglFinish )(void);
void ( APIENTRY * qglFlush )(void);
void ( APIENTRY * qglFogf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglFogfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglFogi )(GLenum pname, GLint param);
void ( APIENTRY * qglFogiv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglFrontFace )(GLenum mode);
void ( APIENTRY * qglFrustum )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint ( APIENTRY * qglGenLists )(GLsizei range);
void ( APIENTRY * qglGenTextures )(GLsizei n, GLuint *textures);
void ( APIENTRY * qglGetBooleanv )(GLenum pname, GLboolean *params);
void ( APIENTRY * qglGetClipPlane )(GLenum plane, GLdouble *equation);
void ( APIENTRY * qglGetDoublev )(GLenum pname, GLdouble *params);
GLenum ( APIENTRY * qglGetError )(void);
void ( APIENTRY * qglGetFloatv )(GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetIntegerv )(GLenum pname, GLint *params);
void ( APIENTRY * qglGetLightfv )(GLenum light, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetLightiv )(GLenum light, GLenum pname, GLint *params);
void ( APIENTRY * qglGetMapdv )(GLenum target, GLenum query, GLdouble *v);
void ( APIENTRY * qglGetMapfv )(GLenum target, GLenum query, GLfloat *v);
void ( APIENTRY * qglGetMapiv )(GLenum target, GLenum query, GLint *v);
void ( APIENTRY * qglGetMaterialfv )(GLenum face, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetMaterialiv )(GLenum face, GLenum pname, GLint *params);
void ( APIENTRY * qglGetPixelMapfv )(GLenum map, GLfloat *values);
void ( APIENTRY * qglGetPixelMapuiv )(GLenum map, GLuint *values);
void ( APIENTRY * qglGetPixelMapusv )(GLenum map, GLushort *values);
void ( APIENTRY * qglGetPointerv )(GLenum pname, GLvoid* *params);
void ( APIENTRY * qglGetPolygonStipple )(GLubyte *mask);
const GLubyte * ( APIENTRY * qglGetString )(GLenum name);
void ( APIENTRY * qglGetTexEnvfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexEnviv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexGendv )(GLenum coord, GLenum pname, GLdouble *params);
void ( APIENTRY * qglGetTexGenfv )(GLenum coord, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexGeniv )(GLenum coord, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexImage )(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglGetTexLevelParameterfv )(GLenum target, GLint level, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexLevelParameteriv )(GLenum target, GLint level, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexParameterfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexParameteriv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglHint )(GLenum target, GLenum mode);
void ( APIENTRY * qglIndexMask )(GLuint mask);
void ( APIENTRY * qglIndexPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglIndexd )(GLdouble c);
void ( APIENTRY * qglIndexdv )(const GLdouble *c);
void ( APIENTRY * qglIndexf )(GLfloat c);
void ( APIENTRY * qglIndexfv )(const GLfloat *c);
void ( APIENTRY * qglIndexi )(GLint c);
void ( APIENTRY * qglIndexiv )(const GLint *c);
void ( APIENTRY * qglIndexs )(GLshort c);
void ( APIENTRY * qglIndexsv )(const GLshort *c);
void ( APIENTRY * qglIndexub )(GLubyte c);
void ( APIENTRY * qglIndexubv )(const GLubyte *c);
void ( APIENTRY * qglInitNames )(void);
void ( APIENTRY * qglInterleavedArrays )(GLenum format, GLsizei stride, const GLvoid *pointer);
GLboolean ( APIENTRY * qglIsEnabled )(GLenum cap);
GLboolean ( APIENTRY * qglIsList )(GLuint list);
GLboolean ( APIENTRY * qglIsTexture )(GLuint texture);
void ( APIENTRY * qglLightModelf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglLightModelfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLightModeli )(GLenum pname, GLint param);
void ( APIENTRY * qglLightModeliv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglLightf )(GLenum light, GLenum pname, GLfloat param);
void ( APIENTRY * qglLightfv )(GLenum light, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLighti )(GLenum light, GLenum pname, GLint param);
void ( APIENTRY * qglLightiv )(GLenum light, GLenum pname, const GLint *params);
void ( APIENTRY * qglLineStipple )(GLint factor, GLushort pattern);
void ( APIENTRY * qglLineWidth )(GLfloat width);
void ( APIENTRY * qglListBase )(GLuint base);
void ( APIENTRY * qglLoadIdentity )(void);
void ( APIENTRY * qglLoadMatrixd )(const GLdouble *m);
void ( APIENTRY * qglLoadMatrixf )(const GLfloat *m);
void ( APIENTRY * qglLoadName )(GLuint name);
void ( APIENTRY * qglLogicOp )(GLenum opcode);
void ( APIENTRY * qglMap1d )(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void ( APIENTRY * qglMap1f )(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void ( APIENTRY * qglMap2d )(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void ( APIENTRY * qglMap2f )(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void ( APIENTRY * qglMapGrid1d )(GLint un, GLdouble u1, GLdouble u2);
void ( APIENTRY * qglMapGrid1f )(GLint un, GLfloat u1, GLfloat u2);
void ( APIENTRY * qglMapGrid2d )(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void ( APIENTRY * qglMapGrid2f )(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void ( APIENTRY * qglMaterialf )(GLenum face, GLenum pname, GLfloat param);
void ( APIENTRY * qglMaterialfv )(GLenum face, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglMateriali )(GLenum face, GLenum pname, GLint param);
void ( APIENTRY * qglMaterialiv )(GLenum face, GLenum pname, const GLint *params);
void ( APIENTRY * qglMatrixMode )(GLenum mode);
void ( APIENTRY * qglMultMatrixd )(const GLdouble *m);
void ( APIENTRY * qglMultMatrixf )(const GLfloat *m);
void ( APIENTRY * qglNewList )(GLuint list, GLenum mode);
void ( APIENTRY * qglNormal3b )(GLbyte nx, GLbyte ny, GLbyte nz);
void ( APIENTRY * qglNormal3bv )(const GLbyte *v);
void ( APIENTRY * qglNormal3d )(GLdouble nx, GLdouble ny, GLdouble nz);
void ( APIENTRY * qglNormal3dv )(const GLdouble *v);
void ( APIENTRY * qglNormal3f )(GLfloat nx, GLfloat ny, GLfloat nz);
void ( APIENTRY * qglNormal3fv )(const GLfloat *v);
void ( APIENTRY * qglNormal3i )(GLint nx, GLint ny, GLint nz);
void ( APIENTRY * qglNormal3iv )(const GLint *v);
void ( APIENTRY * qglNormal3s )(GLshort nx, GLshort ny, GLshort nz);
void ( APIENTRY * qglNormal3sv )(const GLshort *v);
void ( APIENTRY * qglNormalPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglOrtho )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
void ( APIENTRY * qglPassThrough )(GLfloat token);
void ( APIENTRY * qglPixelMapfv )(GLenum map, GLsizei mapsize, const GLfloat *values);
void ( APIENTRY * qglPixelMapuiv )(GLenum map, GLsizei mapsize, const GLuint *values);
void ( APIENTRY * qglPixelMapusv )(GLenum map, GLsizei mapsize, const GLushort *values);
void ( APIENTRY * qglPixelStoref )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelStorei )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelTransferf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelTransferi )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelZoom )(GLfloat xfactor, GLfloat yfactor);
void ( APIENTRY * qglPointSize )(GLfloat size);
void ( APIENTRY * qglPolygonMode )(GLenum face, GLenum mode);
void ( APIENTRY * qglPolygonOffset )(GLfloat factor, GLfloat units);
void ( APIENTRY * qglPolygonStipple )(const GLubyte *mask);
void ( APIENTRY * qglPopAttrib )(void);
void ( APIENTRY * qglPopClientAttrib )(void);
void ( APIENTRY * qglPopMatrix )(void);
void ( APIENTRY * qglPopName )(void);
void ( APIENTRY * qglPrioritizeTextures )(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void ( APIENTRY * qglPushAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushClientAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushMatrix )(void);
void ( APIENTRY * qglPushName )(GLuint name);
void ( APIENTRY * qglRasterPos2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglRasterPos2dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglRasterPos2fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos2i )(GLint x, GLint y);
void ( APIENTRY * qglRasterPos2iv )(const GLint *v);
void ( APIENTRY * qglRasterPos2s )(GLshort x, GLshort y);
void ( APIENTRY * qglRasterPos2sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRasterPos3dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglRasterPos3fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglRasterPos3iv )(const GLint *v);
void ( APIENTRY * qglRasterPos3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglRasterPos3sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglRasterPos4dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglRasterPos4fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglRasterPos4iv )(const GLint *v);
void ( APIENTRY * qglRasterPos4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglRasterPos4sv )(const GLshort *v);
void ( APIENTRY * qglReadBuffer )(GLenum mode);
void ( APIENTRY * qglReadPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglRectd )(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void ( APIENTRY * qglRectdv )(const GLdouble *v1, const GLdouble *v2);
void ( APIENTRY * qglRectf )(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void ( APIENTRY * qglRectfv )(const GLfloat *v1, const GLfloat *v2);
void ( APIENTRY * qglRecti )(GLint x1, GLint y1, GLint x2, GLint y2);
void ( APIENTRY * qglRectiv )(const GLint *v1, const GLint *v2);
void ( APIENTRY * qglRects )(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void ( APIENTRY * qglRectsv )(const GLshort *v1, const GLshort *v2);
GLint ( APIENTRY * qglRenderMode )(GLenum mode);
void ( APIENTRY * qglRotated )(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRotatef )(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScaled )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglScalef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScissor )(GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglSelectBuffer )(GLsizei size, GLuint *buffer);
void ( APIENTRY * qglShadeModel )(GLenum mode);
void ( APIENTRY * qglStencilFunc )(GLenum func, GLint ref, GLuint mask);
void ( APIENTRY * qglStencilMask )(GLuint mask);
void ( APIENTRY * qglStencilOp )(GLenum fail, GLenum zfail, GLenum zpass);
void ( APIENTRY * qglTexCoord1d )(GLdouble s);
void ( APIENTRY * qglTexCoord1dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord1f )(GLfloat s);
void ( APIENTRY * qglTexCoord1fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord1i )(GLint s);
void ( APIENTRY * qglTexCoord1iv )(const GLint *v);
void ( APIENTRY * qglTexCoord1s )(GLshort s);
void ( APIENTRY * qglTexCoord1sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord2d )(GLdouble s, GLdouble t);
void ( APIENTRY * qglTexCoord2dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord2f )(GLfloat s, GLfloat t);
void ( APIENTRY * qglTexCoord2fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord2i )(GLint s, GLint t);
void ( APIENTRY * qglTexCoord2iv )(const GLint *v);
void ( APIENTRY * qglTexCoord2s )(GLshort s, GLshort t);
void ( APIENTRY * qglTexCoord2sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord3d )(GLdouble s, GLdouble t, GLdouble r);
void ( APIENTRY * qglTexCoord3dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord3f )(GLfloat s, GLfloat t, GLfloat r);
void ( APIENTRY * qglTexCoord3fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord3i )(GLint s, GLint t, GLint r);
void ( APIENTRY * qglTexCoord3iv )(const GLint *v);
void ( APIENTRY * qglTexCoord3s )(GLshort s, GLshort t, GLshort r);
void ( APIENTRY * qglTexCoord3sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord4d )(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void ( APIENTRY * qglTexCoord4dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord4f )(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void ( APIENTRY * qglTexCoord4fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord4i )(GLint s, GLint t, GLint r, GLint q);
void ( APIENTRY * qglTexCoord4iv )(const GLint *v);
void ( APIENTRY * qglTexCoord4s )(GLshort s, GLshort t, GLshort r, GLshort q);
void ( APIENTRY * qglTexCoord4sv )(const GLshort *v);
void ( APIENTRY * qglTexCoordPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglTexEnvf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexEnvfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexEnvi )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexEnviv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexGend )(GLenum coord, GLenum pname, GLdouble param);
void ( APIENTRY * qglTexGendv )(GLenum coord, GLenum pname, const GLdouble *params);
void ( APIENTRY * qglTexGenf )(GLenum coord, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexGenfv )(GLenum coord, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexGeni )(GLenum coord, GLenum pname, GLint param);
void ( APIENTRY * qglTexGeniv )(GLenum coord, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexImage1D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexImage2D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexParameterf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexParameterfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexParameteri )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexParameteriv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTranslated )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglTranslatef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglVertex2dv )(const GLdouble *v);
void ( APIENTRY * qglVertex2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglVertex2fv )(const GLfloat *v);
void ( APIENTRY * qglVertex2i )(GLint x, GLint y);
void ( APIENTRY * qglVertex2iv )(const GLint *v);
void ( APIENTRY * qglVertex2s )(GLshort x, GLshort y);
void ( APIENTRY * qglVertex2sv )(const GLshort *v);
void ( APIENTRY * qglVertex3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglVertex3dv )(const GLdouble *v);
void ( APIENTRY * qglVertex3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex3fv )(const GLfloat *v);
void ( APIENTRY * qglVertex3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglVertex3iv )(const GLint *v);
void ( APIENTRY * qglVertex3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglVertex3sv )(const GLshort *v);
void ( APIENTRY * qglVertex4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglVertex4dv )(const GLdouble *v);
void ( APIENTRY * qglVertex4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglVertex4fv )(const GLfloat *v);
void ( APIENTRY * qglVertex4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglVertex4iv )(const GLint *v);
void ( APIENTRY * qglVertex4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglVertex4sv )(const GLshort *v);
void ( APIENTRY * qglVertexPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglViewport )(GLint x, GLint y, GLsizei width, GLsizei height);

void ( APIENTRY * qglLockArraysEXT)( int, int);
void ( APIENTRY * qglUnlockArraysEXT) ( void );

void ( APIENTRY * qglPointParameterfEXT)( GLenum param, GLfloat value );
void ( APIENTRY * qglPointParameterfvEXT)( GLenum param, const GLfloat *value );
void ( APIENTRY * qglColorTableEXT)( int, int, int, int, int, const void * );
void ( APIENTRY * qglSelectTextureSGIS)( GLenum );
void ( APIENTRY * qglMTexCoord2fSGIS)( GLenum, GLfloat, GLfloat );


static void *gl_handle; /* OpenGL.framework handle, kept for process lifetime */

/* dlsym's native type; assigning it to the typed qgl* function pointers
 * is the standard POSIX dlsym idiom */
static void *gpa(const char *name)
{
	return dlsym(gl_handle, name);
}

qboolean QGL_Init(const char *dllname)
{
	(void)dllname; /* the macOS OpenGL framework is always used */

	if (!gl_handle)
	{
		gl_handle = dlopen("/System/Library/Frameworks/OpenGL.framework/OpenGL", RTLD_NOW);
		if (!gl_handle)
			return false;
	}

	qglAccum = gpa("glAccum");
	qglAlphaFunc = gpa("glAlphaFunc");
	qglAreTexturesResident = gpa("glAreTexturesResident");
	qglArrayElement = gpa("glArrayElement");
	qglBegin = gpa("glBegin");
	qglBindTexture = gpa("glBindTexture");
	qglBitmap = gpa("glBitmap");
	qglBlendFunc = gpa("glBlendFunc");
	qglCallList = gpa("glCallList");
	qglCallLists = gpa("glCallLists");
	qglClear = gpa("glClear");
	qglClearAccum = gpa("glClearAccum");
	qglClearColor = gpa("glClearColor");
	qglClearDepth = gpa("glClearDepth");
	qglClearIndex = gpa("glClearIndex");
	qglClearStencil = gpa("glClearStencil");
	qglClipPlane = gpa("glClipPlane");
	qglColor3b = gpa("glColor3b");
	qglColor3bv = gpa("glColor3bv");
	qglColor3d = gpa("glColor3d");
	qglColor3dv = gpa("glColor3dv");
	qglColor3f = gpa("glColor3f");
	qglColor3fv = gpa("glColor3fv");
	qglColor3i = gpa("glColor3i");
	qglColor3iv = gpa("glColor3iv");
	qglColor3s = gpa("glColor3s");
	qglColor3sv = gpa("glColor3sv");
	qglColor3ub = gpa("glColor3ub");
	qglColor3ubv = gpa("glColor3ubv");
	qglColor3ui = gpa("glColor3ui");
	qglColor3uiv = gpa("glColor3uiv");
	qglColor3us = gpa("glColor3us");
	qglColor3usv = gpa("glColor3usv");
	qglColor4b = gpa("glColor4b");
	qglColor4bv = gpa("glColor4bv");
	qglColor4d = gpa("glColor4d");
	qglColor4dv = gpa("glColor4dv");
	qglColor4f = gpa("glColor4f");
	qglColor4fv = gpa("glColor4fv");
	qglColor4i = gpa("glColor4i");
	qglColor4iv = gpa("glColor4iv");
	qglColor4s = gpa("glColor4s");
	qglColor4sv = gpa("glColor4sv");
	qglColor4ub = gpa("glColor4ub");
	qglColor4ubv = gpa("glColor4ubv");
	qglColor4ui = gpa("glColor4ui");
	qglColor4uiv = gpa("glColor4uiv");
	qglColor4us = gpa("glColor4us");
	qglColor4usv = gpa("glColor4usv");
	qglColorMask = gpa("glColorMask");
	qglColorMaterial = gpa("glColorMaterial");
	qglColorPointer = gpa("glColorPointer");
	qglCopyPixels = gpa("glCopyPixels");
	qglCopyTexImage1D = gpa("glCopyTexImage1D");
	qglCopyTexImage2D = gpa("glCopyTexImage2D");
	qglCopyTexSubImage1D = gpa("glCopyTexSubImage1D");
	qglCopyTexSubImage2D = gpa("glCopyTexSubImage2D");
	qglCullFace = gpa("glCullFace");
	qglDeleteLists = gpa("glDeleteLists");
	qglDeleteTextures = gpa("glDeleteTextures");
	qglDepthFunc = gpa("glDepthFunc");
	qglDepthMask = gpa("glDepthMask");
	qglDepthRange = gpa("glDepthRange");
	qglDisable = gpa("glDisable");
	qglDisableClientState = gpa("glDisableClientState");
	qglDrawArrays = gpa("glDrawArrays");
	qglDrawBuffer = gpa("glDrawBuffer");
	qglDrawElements = gpa("glDrawElements");
	qglDrawPixels = gpa("glDrawPixels");
	qglEdgeFlag = gpa("glEdgeFlag");
	qglEdgeFlagPointer = gpa("glEdgeFlagPointer");
	qglEdgeFlagv = gpa("glEdgeFlagv");
	qglEnable = gpa("glEnable");
	qglEnableClientState = gpa("glEnableClientState");
	qglEnd = gpa("glEnd");
	qglEndList = gpa("glEndList");
	qglEvalCoord1d = gpa("glEvalCoord1d");
	qglEvalCoord1dv = gpa("glEvalCoord1dv");
	qglEvalCoord1f = gpa("glEvalCoord1f");
	qglEvalCoord1fv = gpa("glEvalCoord1fv");
	qglEvalCoord2d = gpa("glEvalCoord2d");
	qglEvalCoord2dv = gpa("glEvalCoord2dv");
	qglEvalCoord2f = gpa("glEvalCoord2f");
	qglEvalCoord2fv = gpa("glEvalCoord2fv");
	qglEvalMesh1 = gpa("glEvalMesh1");
	qglEvalMesh2 = gpa("glEvalMesh2");
	qglEvalPoint1 = gpa("glEvalPoint1");
	qglEvalPoint2 = gpa("glEvalPoint2");
	qglFeedbackBuffer = gpa("glFeedbackBuffer");
	qglFinish = gpa("glFinish");
	qglFlush = gpa("glFlush");
	qglFogf = gpa("glFogf");
	qglFogfv = gpa("glFogfv");
	qglFogi = gpa("glFogi");
	qglFogiv = gpa("glFogiv");
	qglFrontFace = gpa("glFrontFace");
	qglFrustum = gpa("glFrustum");
	qglGenLists = gpa("glGenLists");
	qglGenTextures = gpa("glGenTextures");
	qglGetBooleanv = gpa("glGetBooleanv");
	qglGetClipPlane = gpa("glGetClipPlane");
	qglGetDoublev = gpa("glGetDoublev");
	qglGetError = gpa("glGetError");
	qglGetFloatv = gpa("glGetFloatv");
	qglGetIntegerv = gpa("glGetIntegerv");
	qglGetLightfv = gpa("glGetLightfv");
	qglGetLightiv = gpa("glGetLightiv");
	qglGetMapdv = gpa("glGetMapdv");
	qglGetMapfv = gpa("glGetMapfv");
	qglGetMapiv = gpa("glGetMapiv");
	qglGetMaterialfv = gpa("glGetMaterialfv");
	qglGetMaterialiv = gpa("glGetMaterialiv");
	qglGetPixelMapfv = gpa("glGetPixelMapfv");
	qglGetPixelMapuiv = gpa("glGetPixelMapuiv");
	qglGetPixelMapusv = gpa("glGetPixelMapusv");
	qglGetPointerv = gpa("glGetPointerv");
	qglGetPolygonStipple = gpa("glGetPolygonStipple");
	qglGetString = gpa("glGetString");
	qglGetTexEnvfv = gpa("glGetTexEnvfv");
	qglGetTexEnviv = gpa("glGetTexEnviv");
	qglGetTexGendv = gpa("glGetTexGendv");
	qglGetTexGenfv = gpa("glGetTexGenfv");
	qglGetTexGeniv = gpa("glGetTexGeniv");
	qglGetTexImage = gpa("glGetTexImage");
	qglGetTexLevelParameterfv = gpa("glGetTexLevelParameterfv");
	qglGetTexLevelParameteriv = gpa("glGetTexLevelParameteriv");
	qglGetTexParameterfv = gpa("glGetTexParameterfv");
	qglGetTexParameteriv = gpa("glGetTexParameteriv");
	qglHint = gpa("glHint");
	qglIndexMask = gpa("glIndexMask");
	qglIndexPointer = gpa("glIndexPointer");
	qglIndexd = gpa("glIndexd");
	qglIndexdv = gpa("glIndexdv");
	qglIndexf = gpa("glIndexf");
	qglIndexfv = gpa("glIndexfv");
	qglIndexi = gpa("glIndexi");
	qglIndexiv = gpa("glIndexiv");
	qglIndexs = gpa("glIndexs");
	qglIndexsv = gpa("glIndexsv");
	qglIndexub = gpa("glIndexub");
	qglIndexubv = gpa("glIndexubv");
	qglInitNames = gpa("glInitNames");
	qglInterleavedArrays = gpa("glInterleavedArrays");
	qglIsEnabled = gpa("glIsEnabled");
	qglIsList = gpa("glIsList");
	qglIsTexture = gpa("glIsTexture");
	qglLightModelf = gpa("glLightModelf");
	qglLightModelfv = gpa("glLightModelfv");
	qglLightModeli = gpa("glLightModeli");
	qglLightModeliv = gpa("glLightModeliv");
	qglLightf = gpa("glLightf");
	qglLightfv = gpa("glLightfv");
	qglLighti = gpa("glLighti");
	qglLightiv = gpa("glLightiv");
	qglLineStipple = gpa("glLineStipple");
	qglLineWidth = gpa("glLineWidth");
	qglListBase = gpa("glListBase");
	qglLoadIdentity = gpa("glLoadIdentity");
	qglLoadMatrixd = gpa("glLoadMatrixd");
	qglLoadMatrixf = gpa("glLoadMatrixf");
	qglLoadName = gpa("glLoadName");
	qglLogicOp = gpa("glLogicOp");
	qglMap1d = gpa("glMap1d");
	qglMap1f = gpa("glMap1f");
	qglMap2d = gpa("glMap2d");
	qglMap2f = gpa("glMap2f");
	qglMapGrid1d = gpa("glMapGrid1d");
	qglMapGrid1f = gpa("glMapGrid1f");
	qglMapGrid2d = gpa("glMapGrid2d");
	qglMapGrid2f = gpa("glMapGrid2f");
	qglMaterialf = gpa("glMaterialf");
	qglMaterialfv = gpa("glMaterialfv");
	qglMateriali = gpa("glMateriali");
	qglMaterialiv = gpa("glMaterialiv");
	qglMatrixMode = gpa("glMatrixMode");
	qglMultMatrixd = gpa("glMultMatrixd");
	qglMultMatrixf = gpa("glMultMatrixf");
	qglNewList = gpa("glNewList");
	qglNormal3b = gpa("glNormal3b");
	qglNormal3bv = gpa("glNormal3bv");
	qglNormal3d = gpa("glNormal3d");
	qglNormal3dv = gpa("glNormal3dv");
	qglNormal3f = gpa("glNormal3f");
	qglNormal3fv = gpa("glNormal3fv");
	qglNormal3i = gpa("glNormal3i");
	qglNormal3iv = gpa("glNormal3iv");
	qglNormal3s = gpa("glNormal3s");
	qglNormal3sv = gpa("glNormal3sv");
	qglNormalPointer = gpa("glNormalPointer");
	qglOrtho = gpa("glOrtho");
	qglPassThrough = gpa("glPassThrough");
	qglPixelMapfv = gpa("glPixelMapfv");
	qglPixelMapuiv = gpa("glPixelMapuiv");
	qglPixelMapusv = gpa("glPixelMapusv");
	qglPixelStoref = gpa("glPixelStoref");
	qglPixelStorei = gpa("glPixelStorei");
	qglPixelTransferf = gpa("glPixelTransferf");
	qglPixelTransferi = gpa("glPixelTransferi");
	qglPixelZoom = gpa("glPixelZoom");
	qglPointSize = gpa("glPointSize");
	qglPolygonMode = gpa("glPolygonMode");
	qglPolygonOffset = gpa("glPolygonOffset");
	qglPolygonStipple = gpa("glPolygonStipple");
	qglPopAttrib = gpa("glPopAttrib");
	qglPopClientAttrib = gpa("glPopClientAttrib");
	qglPopMatrix = gpa("glPopMatrix");
	qglPopName = gpa("glPopName");
	qglPrioritizeTextures = gpa("glPrioritizeTextures");
	qglPushAttrib = gpa("glPushAttrib");
	qglPushClientAttrib = gpa("glPushClientAttrib");
	qglPushMatrix = gpa("glPushMatrix");
	qglPushName = gpa("glPushName");
	qglRasterPos2d = gpa("glRasterPos2d");
	qglRasterPos2dv = gpa("glRasterPos2dv");
	qglRasterPos2f = gpa("glRasterPos2f");
	qglRasterPos2fv = gpa("glRasterPos2fv");
	qglRasterPos2i = gpa("glRasterPos2i");
	qglRasterPos2iv = gpa("glRasterPos2iv");
	qglRasterPos2s = gpa("glRasterPos2s");
	qglRasterPos2sv = gpa("glRasterPos2sv");
	qglRasterPos3d = gpa("glRasterPos3d");
	qglRasterPos3dv = gpa("glRasterPos3dv");
	qglRasterPos3f = gpa("glRasterPos3f");
	qglRasterPos3fv = gpa("glRasterPos3fv");
	qglRasterPos3i = gpa("glRasterPos3i");
	qglRasterPos3iv = gpa("glRasterPos3iv");
	qglRasterPos3s = gpa("glRasterPos3s");
	qglRasterPos3sv = gpa("glRasterPos3sv");
	qglRasterPos4d = gpa("glRasterPos4d");
	qglRasterPos4dv = gpa("glRasterPos4dv");
	qglRasterPos4f = gpa("glRasterPos4f");
	qglRasterPos4fv = gpa("glRasterPos4fv");
	qglRasterPos4i = gpa("glRasterPos4i");
	qglRasterPos4iv = gpa("glRasterPos4iv");
	qglRasterPos4s = gpa("glRasterPos4s");
	qglRasterPos4sv = gpa("glRasterPos4sv");
	qglReadBuffer = gpa("glReadBuffer");
	qglReadPixels = gpa("glReadPixels");
	qglRectd = gpa("glRectd");
	qglRectdv = gpa("glRectdv");
	qglRectf = gpa("glRectf");
	qglRectfv = gpa("glRectfv");
	qglRecti = gpa("glRecti");
	qglRectiv = gpa("glRectiv");
	qglRects = gpa("glRects");
	qglRectsv = gpa("glRectsv");
	qglRenderMode = gpa("glRenderMode");
	qglRotated = gpa("glRotated");
	qglRotatef = gpa("glRotatef");
	qglScaled = gpa("glScaled");
	qglScalef = gpa("glScalef");
	qglScissor = gpa("glScissor");
	qglSelectBuffer = gpa("glSelectBuffer");
	qglShadeModel = gpa("glShadeModel");
	qglStencilFunc = gpa("glStencilFunc");
	qglStencilMask = gpa("glStencilMask");
	qglStencilOp = gpa("glStencilOp");
	qglTexCoord1d = gpa("glTexCoord1d");
	qglTexCoord1dv = gpa("glTexCoord1dv");
	qglTexCoord1f = gpa("glTexCoord1f");
	qglTexCoord1fv = gpa("glTexCoord1fv");
	qglTexCoord1i = gpa("glTexCoord1i");
	qglTexCoord1iv = gpa("glTexCoord1iv");
	qglTexCoord1s = gpa("glTexCoord1s");
	qglTexCoord1sv = gpa("glTexCoord1sv");
	qglTexCoord2d = gpa("glTexCoord2d");
	qglTexCoord2dv = gpa("glTexCoord2dv");
	qglTexCoord2f = gpa("glTexCoord2f");
	qglTexCoord2fv = gpa("glTexCoord2fv");
	qglTexCoord2i = gpa("glTexCoord2i");
	qglTexCoord2iv = gpa("glTexCoord2iv");
	qglTexCoord2s = gpa("glTexCoord2s");
	qglTexCoord2sv = gpa("glTexCoord2sv");
	qglTexCoord3d = gpa("glTexCoord3d");
	qglTexCoord3dv = gpa("glTexCoord3dv");
	qglTexCoord3f = gpa("glTexCoord3f");
	qglTexCoord3fv = gpa("glTexCoord3fv");
	qglTexCoord3i = gpa("glTexCoord3i");
	qglTexCoord3iv = gpa("glTexCoord3iv");
	qglTexCoord3s = gpa("glTexCoord3s");
	qglTexCoord3sv = gpa("glTexCoord3sv");
	qglTexCoord4d = gpa("glTexCoord4d");
	qglTexCoord4dv = gpa("glTexCoord4dv");
	qglTexCoord4f = gpa("glTexCoord4f");
	qglTexCoord4fv = gpa("glTexCoord4fv");
	qglTexCoord4i = gpa("glTexCoord4i");
	qglTexCoord4iv = gpa("glTexCoord4iv");
	qglTexCoord4s = gpa("glTexCoord4s");
	qglTexCoord4sv = gpa("glTexCoord4sv");
	qglTexCoordPointer = gpa("glTexCoordPointer");
	qglTexEnvf = gpa("glTexEnvf");
	qglTexEnvfv = gpa("glTexEnvfv");
	qglTexEnvi = gpa("glTexEnvi");
	qglTexEnviv = gpa("glTexEnviv");
	qglTexGend = gpa("glTexGend");
	qglTexGendv = gpa("glTexGendv");
	qglTexGenf = gpa("glTexGenf");
	qglTexGenfv = gpa("glTexGenfv");
	qglTexGeni = gpa("glTexGeni");
	qglTexGeniv = gpa("glTexGeniv");
	qglTexImage1D = gpa("glTexImage1D");
	qglTexImage2D = gpa("glTexImage2D");
	qglTexParameterf = gpa("glTexParameterf");
	qglTexParameterfv = gpa("glTexParameterfv");
	qglTexParameteri = gpa("glTexParameteri");
	qglTexParameteriv = gpa("glTexParameteriv");
	qglTexSubImage1D = gpa("glTexSubImage1D");
	qglTexSubImage2D = gpa("glTexSubImage2D");
	qglTranslated = gpa("glTranslated");
	qglTranslatef = gpa("glTranslatef");
	qglVertex2d = gpa("glVertex2d");
	qglVertex2dv = gpa("glVertex2dv");
	qglVertex2f = gpa("glVertex2f");
	qglVertex2fv = gpa("glVertex2fv");
	qglVertex2i = gpa("glVertex2i");
	qglVertex2iv = gpa("glVertex2iv");
	qglVertex2s = gpa("glVertex2s");
	qglVertex2sv = gpa("glVertex2sv");
	qglVertex3d = gpa("glVertex3d");
	qglVertex3dv = gpa("glVertex3dv");
	qglVertex3f = gpa("glVertex3f");
	qglVertex3fv = gpa("glVertex3fv");
	qglVertex3i = gpa("glVertex3i");
	qglVertex3iv = gpa("glVertex3iv");
	qglVertex3s = gpa("glVertex3s");
	qglVertex3sv = gpa("glVertex3sv");
	qglVertex4d = gpa("glVertex4d");
	qglVertex4dv = gpa("glVertex4dv");
	qglVertex4f = gpa("glVertex4f");
	qglVertex4fv = gpa("glVertex4fv");
	qglVertex4i = gpa("glVertex4i");
	qglVertex4iv = gpa("glVertex4iv");
	qglVertex4s = gpa("glVertex4s");
	qglVertex4sv = gpa("glVertex4sv");
	qglVertexPointer = gpa("glVertexPointer");
	qglViewport = gpa("glViewport");

	/* Extension pointers stay NULL on macOS. The OpenGL framework exports
	 * these symbols, but the Metal-backed legacy implementation rejects
	 * their legacy enums (GL_SHARED_TEXTURE_PALETTE_EXT palette uploads,
	 * GL_EXT point parameters, GL_SGIS_multitexture texture units),
	 * raising GL_INVALID_ENUM. The renderer null-checks every one of them
	 * and falls back to its GL 1.1 paths, matching the original Linux
	 * build where they were never resolved either. */

	/* GL 1.1 essentials must exist or the renderer cannot run */
	if (!qglBegin || !qglEnd || !qglBindTexture || !qglTexImage2D ||
		!qglDrawArrays || !qglEnable || !qglDisable || !qglViewport ||
		!qglMatrixMode || !qglLoadIdentity || !qglClearColor || !qglClear ||
		!qglGetError || !qglGetString)
		return false;

	return true;
}

void QGL_Shutdown(void)
{
	/* The qgl* pointers live and die with the ref_gl bundle: all consumers
	 * are inside it, QGL_Init re-resolves every one of them on reload, and
	 * the framework handle is process-lifetime.  Nothing to do. */
}
