// qgl_sdl.c -- qgl function-pointer table for the SDL3 port.
//
// Entry points are resolved by dlopen'ing Apple's OpenGL framework
// directly instead of using SDL_GL_GetProcAddress: SDL cannot resolve GL
// functions until an SDL_WINDOW_OPENGL window has been created, but the
// renderer calls QGL_Init before GLimp_SetMode creates the window.
// dlopen'ing the framework is order-independent. The framework handle is
// process-lifetime (never dlclose'd) so the qgl pointers stay valid
// across vid_restart cycles.
//
// Replaces linux/qgl_linux.c (which assigned compile-time-linked libGL
// symbols). The log/dll wrapper layers are dropped: qgl* point straight at
// the driver entry points; unavailable extensions stay NULL and the
// renderer null-checks them.

#include <dlfcn.h>

#include "../ref_gl/gl_local.h"

/* Global qgl* pointer definitions -- copied verbatim from
 * linux/qgl_linux.c lines 16-361. */
void ( APIENTRY * qglAccum )(GLenum op, GLfloat value);
void ( APIENTRY * qglAlphaFunc )(GLenum func, GLclampf ref);
GLboolean ( APIENTRY * qglAreTexturesResident )(GLsizei n, const GLuint *textures, GLboolean *residences);
void ( APIENTRY * qglArrayElement )(GLint i);
void ( APIENTRY * qglBegin )(GLenum mode);
void ( APIENTRY * qglBindTexture )(GLenum target, GLuint texture);
void ( APIENTRY * qglBitmap )(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void ( APIENTRY * qglBlendFunc )(GLenum sfactor, GLenum dfactor);
void ( APIENTRY * qglCallList )(GLuint list);
void ( APIENTRY * qglCallLists )(GLsizei n, GLenum type, const GLvoid *lists);
void ( APIENTRY * qglClear )(GLbitfield mask);
void ( APIENTRY * qglClearAccum )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglClearColor )(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void ( APIENTRY * qglClearDepth )(GLclampd depth);
void ( APIENTRY * qglClearIndex )(GLfloat c);
void ( APIENTRY * qglClearStencil )(GLint s);
void ( APIENTRY * qglClipPlane )(GLenum plane, const GLdouble *equation);
void ( APIENTRY * qglColor3b )(GLbyte red, GLbyte green, GLbyte blue);
void ( APIENTRY * qglColor3bv )(const GLbyte *v);
void ( APIENTRY * qglColor3d )(GLdouble red, GLdouble green, GLdouble blue);
void ( APIENTRY * qglColor3dv )(const GLdouble *v);
void ( APIENTRY * qglColor3f )(GLfloat red, GLfloat green, GLfloat blue);
void ( APIENTRY * qglColor3fv )(const GLfloat *v);
void ( APIENTRY * qglColor3i )(GLint red, GLint green, GLint blue);
void ( APIENTRY * qglColor3iv )(const GLint *v);
void ( APIENTRY * qglColor3s )(GLshort red, GLshort green, GLshort blue);
void ( APIENTRY * qglColor3sv )(const GLshort *v);
void ( APIENTRY * qglColor3ub )(GLubyte red, GLubyte green, GLubyte blue);
void ( APIENTRY * qglColor3ubv )(const GLubyte *v);
void ( APIENTRY * qglColor3ui )(GLuint red, GLuint green, GLuint blue);
void ( APIENTRY * qglColor3uiv )(const GLuint *v);
void ( APIENTRY * qglColor3us )(GLushort red, GLushort green, GLushort blue);
void ( APIENTRY * qglColor3usv )(const GLushort *v);
void ( APIENTRY * qglColor4b )(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void ( APIENTRY * qglColor4bv )(const GLbyte *v);
void ( APIENTRY * qglColor4d )(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void ( APIENTRY * qglColor4dv )(const GLdouble *v);
void ( APIENTRY * qglColor4f )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglColor4fv )(const GLfloat *v);
void ( APIENTRY * qglColor4i )(GLint red, GLint green, GLint blue, GLint alpha);
void ( APIENTRY * qglColor4iv )(const GLint *v);
void ( APIENTRY * qglColor4s )(GLshort red, GLshort green, GLshort blue, GLshort alpha);
void ( APIENTRY * qglColor4sv )(const GLshort *v);
void ( APIENTRY * qglColor4ub )(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void ( APIENTRY * qglColor4ubv )(const GLubyte *v);
void ( APIENTRY * qglColor4ui )(GLuint red, GLuint green, GLuint blue, GLuint alpha);
void ( APIENTRY * qglColor4uiv )(const GLuint *v);
void ( APIENTRY * qglColor4us )(GLushort red, GLushort green, GLushort blue, GLushort alpha);
void ( APIENTRY * qglColor4usv )(const GLushort *v);
void ( APIENTRY * qglColorMask )(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void ( APIENTRY * qglColorMaterial )(GLenum face, GLenum mode);
void ( APIENTRY * qglColorPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglCopyPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void ( APIENTRY * qglCopyTexImage1D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
void ( APIENTRY * qglCopyTexImage2D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void ( APIENTRY * qglCopyTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void ( APIENTRY * qglCopyTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglCullFace )(GLenum mode);
void ( APIENTRY * qglDeleteLists )(GLuint list, GLsizei range);
void ( APIENTRY * qglDeleteTextures )(GLsizei n, const GLuint *textures);
void ( APIENTRY * qglDepthFunc )(GLenum func);
void ( APIENTRY * qglDepthMask )(GLboolean flag);
void ( APIENTRY * qglDepthRange )(GLclampd zNear, GLclampd zFar);
void ( APIENTRY * qglDisable )(GLenum cap);
void ( APIENTRY * qglDisableClientState )(GLenum array);
void ( APIENTRY * qglDrawArrays )(GLenum mode, GLint first, GLsizei count);
void ( APIENTRY * qglDrawBuffer )(GLenum mode);
void ( APIENTRY * qglDrawElements )(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void ( APIENTRY * qglDrawPixels )(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglEdgeFlag )(GLboolean flag);
void ( APIENTRY * qglEdgeFlagPointer )(GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglEdgeFlagv )(const GLboolean *flag);
void ( APIENTRY * qglEnable )(GLenum cap);
void ( APIENTRY * qglEnableClientState )(GLenum array);
void ( APIENTRY * qglEnd )(void);
void ( APIENTRY * qglEndList )(void);
void ( APIENTRY * qglEvalCoord1d )(GLdouble u);
void ( APIENTRY * qglEvalCoord1dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord1f )(GLfloat u);
void ( APIENTRY * qglEvalCoord1fv )(const GLfloat *u);
void ( APIENTRY * qglEvalCoord2d )(GLdouble u, GLdouble v);
void ( APIENTRY * qglEvalCoord2dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord2f )(GLfloat u, GLfloat v);
void ( APIENTRY * qglEvalCoord2fv )(const GLfloat *u);
void ( APIENTRY * qglEvalMesh1 )(GLenum mode, GLint i1, GLint i2);
void ( APIENTRY * qglEvalMesh2 )(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void ( APIENTRY * qglEvalPoint1 )(GLint i);
void ( APIENTRY * qglEvalPoint2 )(GLint i, GLint j);
void ( APIENTRY * qglFeedbackBuffer )(GLsizei size, GLenum type, GLfloat *buffer);
void ( APIENTRY * qglFinish )(void);
void ( APIENTRY * qglFlush )(void);
void ( APIENTRY * qglFogf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglFogfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglFogi )(GLenum pname, GLint param);
void ( APIENTRY * qglFogiv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglFrontFace )(GLenum mode);
void ( APIENTRY * qglFrustum )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint ( APIENTRY * qglGenLists )(GLsizei range);
void ( APIENTRY * qglGenTextures )(GLsizei n, GLuint *textures);
void ( APIENTRY * qglGetBooleanv )(GLenum pname, GLboolean *params);
void ( APIENTRY * qglGetClipPlane )(GLenum plane, GLdouble *equation);
void ( APIENTRY * qglGetDoublev )(GLenum pname, GLdouble *params);
GLenum ( APIENTRY * qglGetError )(void);
void ( APIENTRY * qglGetFloatv )(GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetIntegerv )(GLenum pname, GLint *params);
void ( APIENTRY * qglGetLightfv )(GLenum light, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetLightiv )(GLenum light, GLenum pname, GLint *params);
void ( APIENTRY * qglGetMapdv )(GLenum target, GLenum query, GLdouble *v);
void ( APIENTRY * qglGetMapfv )(GLenum target, GLenum query, GLfloat *v);
void ( APIENTRY * qglGetMapiv )(GLenum target, GLenum query, GLint *v);
void ( APIENTRY * qglGetMaterialfv )(GLenum face, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetMaterialiv )(GLenum face, GLenum pname, GLint *params);
void ( APIENTRY * qglGetPixelMapfv )(GLenum map, GLfloat *values);
void ( APIENTRY * qglGetPixelMapuiv )(GLenum map, GLuint *values);
void ( APIENTRY * qglGetPixelMapusv )(GLenum map, GLushort *values);
void ( APIENTRY * qglGetPointerv )(GLenum pname, GLvoid* *params);
void ( APIENTRY * qglGetPolygonStipple )(GLubyte *mask);
const GLubyte * ( APIENTRY * qglGetString )(GLenum name);
void ( APIENTRY * qglGetTexEnvfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexEnviv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexGendv )(GLenum coord, GLenum pname, GLdouble *params);
void ( APIENTRY * qglGetTexGenfv )(GLenum coord, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexGeniv )(GLenum coord, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexImage )(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglGetTexLevelParameterfv )(GLenum target, GLint level, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexLevelParameteriv )(GLenum target, GLint level, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexParameterfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexParameteriv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglHint )(GLenum target, GLenum mode);
void ( APIENTRY * qglIndexMask )(GLuint mask);
void ( APIENTRY * qglIndexPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglIndexd )(GLdouble c);
void ( APIENTRY * qglIndexdv )(const GLdouble *c);
void ( APIENTRY * qglIndexf )(GLfloat c);
void ( APIENTRY * qglIndexfv )(const GLfloat *c);
void ( APIENTRY * qglIndexi )(GLint c);
void ( APIENTRY * qglIndexiv )(const GLint *c);
void ( APIENTRY * qglIndexs )(GLshort c);
void ( APIENTRY * qglIndexsv )(const GLshort *c);
void ( APIENTRY * qglIndexub )(GLubyte c);
void ( APIENTRY * qglIndexubv )(const GLubyte *c);
void ( APIENTRY * qglInitNames )(void);
void ( APIENTRY * qglInterleavedArrays )(GLenum format, GLsizei stride, const GLvoid *pointer);
GLboolean ( APIENTRY * qglIsEnabled )(GLenum cap);
GLboolean ( APIENTRY * qglIsList )(GLuint list);
GLboolean ( APIENTRY * qglIsTexture )(GLuint texture);
void ( APIENTRY * qglLightModelf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglLightModelfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLightModeli )(GLenum pname, GLint param);
void ( APIENTRY * qglLightModeliv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglLightf )(GLenum light, GLenum pname, GLfloat param);
void ( APIENTRY * qglLightfv )(GLenum light, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLighti )(GLenum light, GLenum pname, GLint param);
void ( APIENTRY * qglLightiv )(GLenum light, GLenum pname, const GLint *params);
void ( APIENTRY * qglLineStipple )(GLint factor, GLushort pattern);
void ( APIENTRY * qglLineWidth )(GLfloat width);
void ( APIENTRY * qglListBase )(GLuint base);
void ( APIENTRY * qglLoadIdentity )(void);
void ( APIENTRY * qglLoadMatrixd )(const GLdouble *m);
void ( APIENTRY * qglLoadMatrixf )(const GLfloat *m);
void ( APIENTRY * qglLoadName )(GLuint name);
void ( APIENTRY * qglLogicOp )(GLenum opcode);
void ( APIENTRY * qglMap1d )(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void ( APIENTRY * qglMap1f )(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void ( APIENTRY * qglMap2d )(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void ( APIENTRY * qglMap2f )(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void ( APIENTRY * qglMapGrid1d )(GLint un, GLdouble u1, GLdouble u2);
void ( APIENTRY * qglMapGrid1f )(GLint un, GLfloat u1, GLfloat u2);
void ( APIENTRY * qglMapGrid2d )(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void ( APIENTRY * qglMapGrid2f )(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void ( APIENTRY * qglMaterialf )(GLenum face, GLenum pname, GLfloat param);
void ( APIENTRY * qglMaterialfv )(GLenum face, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglMateriali )(GLenum face, GLenum pname, GLint param);
void ( APIENTRY * qglMaterialiv )(GLenum face, GLenum pname, const GLint *params);
void ( APIENTRY * qglMatrixMode )(GLenum mode);
void ( APIENTRY * qglMultMatrixd )(const GLdouble *m);
void ( APIENTRY * qglMultMatrixf )(const GLfloat *m);
void ( APIENTRY * qglNewList )(GLuint list, GLenum mode);
void ( APIENTRY * qglNormal3b )(GLbyte nx, GLbyte ny, GLbyte nz);
void ( APIENTRY * qglNormal3bv )(const GLbyte *v);
void ( APIENTRY * qglNormal3d )(GLdouble nx, GLdouble ny, GLdouble nz);
void ( APIENTRY * qglNormal3dv )(const GLdouble *v);
void ( APIENTRY * qglNormal3f )(GLfloat nx, GLfloat ny, GLfloat nz);
void ( APIENTRY * qglNormal3fv )(const GLfloat *v);
void ( APIENTRY * qglNormal3i )(GLint nx, GLint ny, GLint nz);
void ( APIENTRY * qglNormal3iv )(const GLint *v);
void ( APIENTRY * qglNormal3s )(GLshort nx, GLshort ny, GLshort nz);
void ( APIENTRY * qglNormal3sv )(const GLshort *v);
void ( APIENTRY * qglNormalPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglOrtho )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
void ( APIENTRY * qglPassThrough )(GLfloat token);
void ( APIENTRY * qglPixelMapfv )(GLenum map, GLsizei mapsize, const GLfloat *values);
void ( APIENTRY * qglPixelMapuiv )(GLenum map, GLsizei mapsize, const GLuint *values);
void ( APIENTRY * qglPixelMapusv )(GLenum map, GLsizei mapsize, const GLushort *values);
void ( APIENTRY * qglPixelStoref )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelStorei )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelTransferf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelTransferi )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelZoom )(GLfloat xfactor, GLfloat yfactor);
void ( APIENTRY * qglPointSize )(GLfloat size);
void ( APIENTRY * qglPolygonMode )(GLenum face, GLenum mode);
void ( APIENTRY * qglPolygonOffset )(GLfloat factor, GLfloat units);
void ( APIENTRY * qglPolygonStipple )(const GLubyte *mask);
void ( APIENTRY * qglPopAttrib )(void);
void ( APIENTRY * qglPopClientAttrib )(void);
void ( APIENTRY * qglPopMatrix )(void);
void ( APIENTRY * qglPopName )(void);
void ( APIENTRY * qglPrioritizeTextures )(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void ( APIENTRY * qglPushAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushClientAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushMatrix )(void);
void ( APIENTRY * qglPushName )(GLuint name);
void ( APIENTRY * qglRasterPos2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglRasterPos2dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglRasterPos2fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos2i )(GLint x, GLint y);
void ( APIENTRY * qglRasterPos2iv )(const GLint *v);
void ( APIENTRY * qglRasterPos2s )(GLshort x, GLshort y);
void ( APIENTRY * qglRasterPos2sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRasterPos3dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglRasterPos3fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglRasterPos3iv )(const GLint *v);
void ( APIENTRY * qglRasterPos3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglRasterPos3sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglRasterPos4dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglRasterPos4fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglRasterPos4iv )(const GLint *v);
void ( APIENTRY * qglRasterPos4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglRasterPos4sv )(const GLshort *v);
void ( APIENTRY * qglReadBuffer )(GLenum mode);
void ( APIENTRY * qglReadPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglRectd )(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void ( APIENTRY * qglRectdv )(const GLdouble *v1, const GLdouble *v2);
void ( APIENTRY * qglRectf )(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void ( APIENTRY * qglRectfv )(const GLfloat *v1, const GLfloat *v2);
void ( APIENTRY * qglRecti )(GLint x1, GLint y1, GLint x2, GLint y2);
void ( APIENTRY * qglRectiv )(const GLint *v1, const GLint *v2);
void ( APIENTRY * qglRects )(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void ( APIENTRY * qglRectsv )(const GLshort *v1, const GLshort *v2);
GLint ( APIENTRY * qglRenderMode )(GLenum mode);
void ( APIENTRY * qglRotated )(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRotatef )(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScaled )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglScalef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScissor )(GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglSelectBuffer )(GLsizei size, GLuint *buffer);
void ( APIENTRY * qglShadeModel )(GLenum mode);
void ( APIENTRY * qglStencilFunc )(GLenum func, GLint ref, GLuint mask);
void ( APIENTRY * qglStencilMask )(GLuint mask);
void ( APIENTRY * qglStencilOp )(GLenum fail, GLenum zfail, GLenum zpass);
void ( APIENTRY * qglTexCoord1d )(GLdouble s);
void ( APIENTRY * qglTexCoord1dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord1f )(GLfloat s);
void ( APIENTRY * qglTexCoord1fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord1i )(GLint s);
void ( APIENTRY * qglTexCoord1iv )(const GLint *v);
void ( APIENTRY * qglTexCoord1s )(GLshort s);
void ( APIENTRY * qglTexCoord1sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord2d )(GLdouble s, GLdouble t);
void ( APIENTRY * qglTexCoord2dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord2f )(GLfloat s, GLfloat t);
void ( APIENTRY * qglTexCoord2fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord2i )(GLint s, GLint t);
void ( APIENTRY * qglTexCoord2iv )(const GLint *v);
void ( APIENTRY * qglTexCoord2s )(GLshort s, GLshort t);
void ( APIENTRY * qglTexCoord2sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord3d )(GLdouble s, GLdouble t, GLdouble r);
void ( APIENTRY * qglTexCoord3dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord3f )(GLfloat s, GLfloat t, GLfloat r);
void ( APIENTRY * qglTexCoord3fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord3i )(GLint s, GLint t, GLint r);
void ( APIENTRY * qglTexCoord3iv )(const GLint *v);
void ( APIENTRY * qglTexCoord3s )(GLshort s, GLshort t, GLshort r);
void ( APIENTRY * qglTexCoord3sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord4d )(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void ( APIENTRY * qglTexCoord4dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord4f )(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void ( APIENTRY * qglTexCoord4fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord4i )(GLint s, GLint t, GLint r, GLint q);
void ( APIENTRY * qglTexCoord4iv )(const GLint *v);
void ( APIENTRY * qglTexCoord4s )(GLshort s, GLshort t, GLshort r, GLshort q);
void ( APIENTRY * qglTexCoord4sv )(const GLshort *v);
void ( APIENTRY * qglTexCoordPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglTexEnvf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexEnvfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexEnvi )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexEnviv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexGend )(GLenum coord, GLenum pname, GLdouble param);
void ( APIENTRY * qglTexGendv )(GLenum coord, GLenum pname, const GLdouble *params);
void ( APIENTRY * qglTexGenf )(GLenum coord, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexGenfv )(GLenum coord, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexGeni )(GLenum coord, GLenum pname, GLint param);
void ( APIENTRY * qglTexGeniv )(GLenum coord, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexImage1D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexImage2D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexParameterf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexParameterfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexParameteri )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexParameteriv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTranslated )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglTranslatef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglVertex2dv )(const GLdouble *v);
void ( APIENTRY * qglVertex2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglVertex2fv )(const GLfloat *v);
void ( APIENTRY * qglVertex2i )(GLint x, GLint y);
void ( APIENTRY * qglVertex2iv )(const GLint *v);
void ( APIENTRY * qglVertex2s )(GLshort x, GLshort y);
void ( APIENTRY * qglVertex2sv )(const GLshort *v);
void ( APIENTRY * qglVertex3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglVertex3dv )(const GLdouble *v);
void ( APIENTRY * qglVertex3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex3fv )(const GLfloat *v);
void ( APIENTRY * qglVertex3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglVertex3iv )(const GLint *v);
void ( APIENTRY * qglVertex3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglVertex3sv )(const GLshort *v);
void ( APIENTRY * qglVertex4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglVertex4dv )(const GLdouble *v);
void ( APIENTRY * qglVertex4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglVertex4fv )(const GLfloat *v);
void ( APIENTRY * qglVertex4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglVertex4iv )(const GLint *v);
void ( APIENTRY * qglVertex4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglVertex4sv )(const GLshort *v);
void ( APIENTRY * qglVertexPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglViewport )(GLint x, GLint y, GLsizei width, GLsizei height);

void ( APIENTRY * qglLockArraysEXT)( int, int);
void ( APIENTRY * qglUnlockArraysEXT) ( void );

void ( APIENTRY * qglPointParameterfEXT)( GLenum param, GLfloat value );
void ( APIENTRY * qglPointParameterfvEXT)( GLenum param, const GLfloat *value );
void ( APIENTRY * qglColorTableEXT)( int, int, int, int, int, const void * );
void ( APIENTRY * qglSelectTextureSGIS)( GLenum );
void ( APIENTRY * qglMTexCoord2fSGIS)( GLenum, GLfloat, GLfloat );


typedef void (*glproc_t)(void);

static void *gl_handle; /* OpenGL.framework handle, kept for process lifetime */

static glproc_t gpa(const char *name)
{
	return (glproc_t)dlsym(gl_handle, name);
}

qboolean QGL_Init(const char *dllname)
{
	(void)dllname; /* the macOS OpenGL framework is always used */

	if (!gl_handle)
	{
		gl_handle = dlopen("/System/Library/Frameworks/OpenGL.framework/OpenGL", RTLD_NOW);
		if (!gl_handle)
			return false;
	}

	qglAccum = (void (APIENTRY *)(GLenum op, GLfloat value))gpa("glAccum");
	qglAlphaFunc = (void (APIENTRY *)(GLenum func, GLclampf ref))gpa("glAlphaFunc");
	qglAreTexturesResident = (GLboolean (APIENTRY *)(GLsizei n, const GLuint *textures, GLboolean *residences))gpa("glAreTexturesResident");
	qglArrayElement = (void (APIENTRY *)(GLint i))gpa("glArrayElement");
	qglBegin = (void (APIENTRY *)(GLenum mode))gpa("glBegin");
	qglBindTexture = (void (APIENTRY *)(GLenum target, GLuint texture))gpa("glBindTexture");
	qglBitmap = (void (APIENTRY *)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap))gpa("glBitmap");
	qglBlendFunc = (void (APIENTRY *)(GLenum sfactor, GLenum dfactor))gpa("glBlendFunc");
	qglCallList = (void (APIENTRY *)(GLuint list))gpa("glCallList");
	qglCallLists = (void (APIENTRY *)(GLsizei n, GLenum type, const GLvoid *lists))gpa("glCallLists");
	qglClear = (void (APIENTRY *)(GLbitfield mask))gpa("glClear");
	qglClearAccum = (void (APIENTRY *)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))gpa("glClearAccum");
	qglClearColor = (void (APIENTRY *)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha))gpa("glClearColor");
	qglClearDepth = (void (APIENTRY *)(GLclampd depth))gpa("glClearDepth");
	qglClearIndex = (void (APIENTRY *)(GLfloat c))gpa("glClearIndex");
	qglClearStencil = (void (APIENTRY *)(GLint s))gpa("glClearStencil");
	qglClipPlane = (void (APIENTRY *)(GLenum plane, const GLdouble *equation))gpa("glClipPlane");
	qglColor3b = (void (APIENTRY *)(GLbyte red, GLbyte green, GLbyte blue))gpa("glColor3b");
	qglColor3bv = (void (APIENTRY *)(const GLbyte *v))gpa("glColor3bv");
	qglColor3d = (void (APIENTRY *)(GLdouble red, GLdouble green, GLdouble blue))gpa("glColor3d");
	qglColor3dv = (void (APIENTRY *)(const GLdouble *v))gpa("glColor3dv");
	qglColor3f = (void (APIENTRY *)(GLfloat red, GLfloat green, GLfloat blue))gpa("glColor3f");
	qglColor3fv = (void (APIENTRY *)(const GLfloat *v))gpa("glColor3fv");
	qglColor3i = (void (APIENTRY *)(GLint red, GLint green, GLint blue))gpa("glColor3i");
	qglColor3iv = (void (APIENTRY *)(const GLint *v))gpa("glColor3iv");
	qglColor3s = (void (APIENTRY *)(GLshort red, GLshort green, GLshort blue))gpa("glColor3s");
	qglColor3sv = (void (APIENTRY *)(const GLshort *v))gpa("glColor3sv");
	qglColor3ub = (void (APIENTRY *)(GLubyte red, GLubyte green, GLubyte blue))gpa("glColor3ub");
	qglColor3ubv = (void (APIENTRY *)(const GLubyte *v))gpa("glColor3ubv");
	qglColor3ui = (void (APIENTRY *)(GLuint red, GLuint green, GLuint blue))gpa("glColor3ui");
	qglColor3uiv = (void (APIENTRY *)(const GLuint *v))gpa("glColor3uiv");
	qglColor3us = (void (APIENTRY *)(GLushort red, GLushort green, GLushort blue))gpa("glColor3us");
	qglColor3usv = (void (APIENTRY *)(const GLushort *v))gpa("glColor3usv");
	qglColor4b = (void (APIENTRY *)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha))gpa("glColor4b");
	qglColor4bv = (void (APIENTRY *)(const GLbyte *v))gpa("glColor4bv");
	qglColor4d = (void (APIENTRY *)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha))gpa("glColor4d");
	qglColor4dv = (void (APIENTRY *)(const GLdouble *v))gpa("glColor4dv");
	qglColor4f = (void (APIENTRY *)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))gpa("glColor4f");
	qglColor4fv = (void (APIENTRY *)(const GLfloat *v))gpa("glColor4fv");
	qglColor4i = (void (APIENTRY *)(GLint red, GLint green, GLint blue, GLint alpha))gpa("glColor4i");
	qglColor4iv = (void (APIENTRY *)(const GLint *v))gpa("glColor4iv");
	qglColor4s = (void (APIENTRY *)(GLshort red, GLshort green, GLshort blue, GLshort alpha))gpa("glColor4s");
	qglColor4sv = (void (APIENTRY *)(const GLshort *v))gpa("glColor4sv");
	qglColor4ub = (void (APIENTRY *)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))gpa("glColor4ub");
	qglColor4ubv = (void (APIENTRY *)(const GLubyte *v))gpa("glColor4ubv");
	qglColor4ui = (void (APIENTRY *)(GLuint red, GLuint green, GLuint blue, GLuint alpha))gpa("glColor4ui");
	qglColor4uiv = (void (APIENTRY *)(const GLuint *v))gpa("glColor4uiv");
	qglColor4us = (void (APIENTRY *)(GLushort red, GLushort green, GLushort blue, GLushort alpha))gpa("glColor4us");
	qglColor4usv = (void (APIENTRY *)(const GLushort *v))gpa("glColor4usv");
	qglColorMask = (void (APIENTRY *)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))gpa("glColorMask");
	qglColorMaterial = (void (APIENTRY *)(GLenum face, GLenum mode))gpa("glColorMaterial");
	qglColorPointer = (void (APIENTRY *)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))gpa("glColorPointer");
	qglCopyPixels = (void (APIENTRY *)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type))gpa("glCopyPixels");
	qglCopyTexImage1D = (void (APIENTRY *)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border))gpa("glCopyTexImage1D");
	qglCopyTexImage2D = (void (APIENTRY *)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))gpa("glCopyTexImage2D");
	qglCopyTexSubImage1D = (void (APIENTRY *)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width))gpa("glCopyTexSubImage1D");
	qglCopyTexSubImage2D = (void (APIENTRY *)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))gpa("glCopyTexSubImage2D");
	qglCullFace = (void (APIENTRY *)(GLenum mode))gpa("glCullFace");
	qglDeleteLists = (void (APIENTRY *)(GLuint list, GLsizei range))gpa("glDeleteLists");
	qglDeleteTextures = (void (APIENTRY *)(GLsizei n, const GLuint *textures))gpa("glDeleteTextures");
	qglDepthFunc = (void (APIENTRY *)(GLenum func))gpa("glDepthFunc");
	qglDepthMask = (void (APIENTRY *)(GLboolean flag))gpa("glDepthMask");
	qglDepthRange = (void (APIENTRY *)(GLclampd zNear, GLclampd zFar))gpa("glDepthRange");
	qglDisable = (void (APIENTRY *)(GLenum cap))gpa("glDisable");
	qglDisableClientState = (void (APIENTRY *)(GLenum array))gpa("glDisableClientState");
	qglDrawArrays = (void (APIENTRY *)(GLenum mode, GLint first, GLsizei count))gpa("glDrawArrays");
	qglDrawBuffer = (void (APIENTRY *)(GLenum mode))gpa("glDrawBuffer");
	qglDrawElements = (void (APIENTRY *)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices))gpa("glDrawElements");
	qglDrawPixels = (void (APIENTRY *)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))gpa("glDrawPixels");
	qglEdgeFlag = (void (APIENTRY *)(GLboolean flag))gpa("glEdgeFlag");
	qglEdgeFlagPointer = (void (APIENTRY *)(GLsizei stride, const GLvoid *pointer))gpa("glEdgeFlagPointer");
	qglEdgeFlagv = (void (APIENTRY *)(const GLboolean *flag))gpa("glEdgeFlagv");
	qglEnable = (void (APIENTRY *)(GLenum cap))gpa("glEnable");
	qglEnableClientState = (void (APIENTRY *)(GLenum array))gpa("glEnableClientState");
	qglEnd = (void (APIENTRY *)(void))gpa("glEnd");
	qglEndList = (void (APIENTRY *)(void))gpa("glEndList");
	qglEvalCoord1d = (void (APIENTRY *)(GLdouble u))gpa("glEvalCoord1d");
	qglEvalCoord1dv = (void (APIENTRY *)(const GLdouble *u))gpa("glEvalCoord1dv");
	qglEvalCoord1f = (void (APIENTRY *)(GLfloat u))gpa("glEvalCoord1f");
	qglEvalCoord1fv = (void (APIENTRY *)(const GLfloat *u))gpa("glEvalCoord1fv");
	qglEvalCoord2d = (void (APIENTRY *)(GLdouble u, GLdouble v))gpa("glEvalCoord2d");
	qglEvalCoord2dv = (void (APIENTRY *)(const GLdouble *u))gpa("glEvalCoord2dv");
	qglEvalCoord2f = (void (APIENTRY *)(GLfloat u, GLfloat v))gpa("glEvalCoord2f");
	qglEvalCoord2fv = (void (APIENTRY *)(const GLfloat *u))gpa("glEvalCoord2fv");
	qglEvalMesh1 = (void (APIENTRY *)(GLenum mode, GLint i1, GLint i2))gpa("glEvalMesh1");
	qglEvalMesh2 = (void (APIENTRY *)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2))gpa("glEvalMesh2");
	qglEvalPoint1 = (void (APIENTRY *)(GLint i))gpa("glEvalPoint1");
	qglEvalPoint2 = (void (APIENTRY *)(GLint i, GLint j))gpa("glEvalPoint2");
	qglFeedbackBuffer = (void (APIENTRY *)(GLsizei size, GLenum type, GLfloat *buffer))gpa("glFeedbackBuffer");
	qglFinish = (void (APIENTRY *)(void))gpa("glFinish");
	qglFlush = (void (APIENTRY *)(void))gpa("glFlush");
	qglFogf = (void (APIENTRY *)(GLenum pname, GLfloat param))gpa("glFogf");
	qglFogfv = (void (APIENTRY *)(GLenum pname, const GLfloat *params))gpa("glFogfv");
	qglFogi = (void (APIENTRY *)(GLenum pname, GLint param))gpa("glFogi");
	qglFogiv = (void (APIENTRY *)(GLenum pname, const GLint *params))gpa("glFogiv");
	qglFrontFace = (void (APIENTRY *)(GLenum mode))gpa("glFrontFace");
	qglFrustum = (void (APIENTRY *)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))gpa("glFrustum");
	qglGenLists = (GLuint (APIENTRY *)(GLsizei range))gpa("glGenLists");
	qglGenTextures = (void (APIENTRY *)(GLsizei n, GLuint *textures))gpa("glGenTextures");
	qglGetBooleanv = (void (APIENTRY *)(GLenum pname, GLboolean *params))gpa("glGetBooleanv");
	qglGetClipPlane = (void (APIENTRY *)(GLenum plane, GLdouble *equation))gpa("glGetClipPlane");
	qglGetDoublev = (void (APIENTRY *)(GLenum pname, GLdouble *params))gpa("glGetDoublev");
	qglGetError = (GLenum (APIENTRY *)(void))gpa("glGetError");
	qglGetFloatv = (void (APIENTRY *)(GLenum pname, GLfloat *params))gpa("glGetFloatv");
	qglGetIntegerv = (void (APIENTRY *)(GLenum pname, GLint *params))gpa("glGetIntegerv");
	qglGetLightfv = (void (APIENTRY *)(GLenum light, GLenum pname, GLfloat *params))gpa("glGetLightfv");
	qglGetLightiv = (void (APIENTRY *)(GLenum light, GLenum pname, GLint *params))gpa("glGetLightiv");
	qglGetMapdv = (void (APIENTRY *)(GLenum target, GLenum query, GLdouble *v))gpa("glGetMapdv");
	qglGetMapfv = (void (APIENTRY *)(GLenum target, GLenum query, GLfloat *v))gpa("glGetMapfv");
	qglGetMapiv = (void (APIENTRY *)(GLenum target, GLenum query, GLint *v))gpa("glGetMapiv");
	qglGetMaterialfv = (void (APIENTRY *)(GLenum face, GLenum pname, GLfloat *params))gpa("glGetMaterialfv");
	qglGetMaterialiv = (void (APIENTRY *)(GLenum face, GLenum pname, GLint *params))gpa("glGetMaterialiv");
	qglGetPixelMapfv = (void (APIENTRY *)(GLenum map, GLfloat *values))gpa("glGetPixelMapfv");
	qglGetPixelMapuiv = (void (APIENTRY *)(GLenum map, GLuint *values))gpa("glGetPixelMapuiv");
	qglGetPixelMapusv = (void (APIENTRY *)(GLenum map, GLushort *values))gpa("glGetPixelMapusv");
	qglGetPointerv = (void (APIENTRY *)(GLenum pname, GLvoid* *params))gpa("glGetPointerv");
	qglGetPolygonStipple = (void (APIENTRY *)(GLubyte *mask))gpa("glGetPolygonStipple");
	qglGetString = (const GLubyte * (APIENTRY *)(GLenum name))gpa("glGetString");
	qglGetTexEnvfv = (void (APIENTRY *)(GLenum target, GLenum pname, GLfloat *params))gpa("glGetTexEnvfv");
	qglGetTexEnviv = (void (APIENTRY *)(GLenum target, GLenum pname, GLint *params))gpa("glGetTexEnviv");
	qglGetTexGendv = (void (APIENTRY *)(GLenum coord, GLenum pname, GLdouble *params))gpa("glGetTexGendv");
	qglGetTexGenfv = (void (APIENTRY *)(GLenum coord, GLenum pname, GLfloat *params))gpa("glGetTexGenfv");
	qglGetTexGeniv = (void (APIENTRY *)(GLenum coord, GLenum pname, GLint *params))gpa("glGetTexGeniv");
	qglGetTexImage = (void (APIENTRY *)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels))gpa("glGetTexImage");
	qglGetTexLevelParameterfv = (void (APIENTRY *)(GLenum target, GLint level, GLenum pname, GLfloat *params))gpa("glGetTexLevelParameterfv");
	qglGetTexLevelParameteriv = (void (APIENTRY *)(GLenum target, GLint level, GLenum pname, GLint *params))gpa("glGetTexLevelParameteriv");
	qglGetTexParameterfv = (void (APIENTRY *)(GLenum target, GLenum pname, GLfloat *params))gpa("glGetTexParameterfv");
	qglGetTexParameteriv = (void (APIENTRY *)(GLenum target, GLenum pname, GLint *params))gpa("glGetTexParameteriv");
	qglHint = (void (APIENTRY *)(GLenum target, GLenum mode))gpa("glHint");
	qglIndexMask = (void (APIENTRY *)(GLuint mask))gpa("glIndexMask");
	qglIndexPointer = (void (APIENTRY *)(GLenum type, GLsizei stride, const GLvoid *pointer))gpa("glIndexPointer");
	qglIndexd = (void (APIENTRY *)(GLdouble c))gpa("glIndexd");
	qglIndexdv = (void (APIENTRY *)(const GLdouble *c))gpa("glIndexdv");
	qglIndexf = (void (APIENTRY *)(GLfloat c))gpa("glIndexf");
	qglIndexfv = (void (APIENTRY *)(const GLfloat *c))gpa("glIndexfv");
	qglIndexi = (void (APIENTRY *)(GLint c))gpa("glIndexi");
	qglIndexiv = (void (APIENTRY *)(const GLint *c))gpa("glIndexiv");
	qglIndexs = (void (APIENTRY *)(GLshort c))gpa("glIndexs");
	qglIndexsv = (void (APIENTRY *)(const GLshort *c))gpa("glIndexsv");
	qglIndexub = (void (APIENTRY *)(GLubyte c))gpa("glIndexub");
	qglIndexubv = (void (APIENTRY *)(const GLubyte *c))gpa("glIndexubv");
	qglInitNames = (void (APIENTRY *)(void))gpa("glInitNames");
	qglInterleavedArrays = (void (APIENTRY *)(GLenum format, GLsizei stride, const GLvoid *pointer))gpa("glInterleavedArrays");
	qglIsEnabled = (GLboolean (APIENTRY *)(GLenum cap))gpa("glIsEnabled");
	qglIsList = (GLboolean (APIENTRY *)(GLuint list))gpa("glIsList");
	qglIsTexture = (GLboolean (APIENTRY *)(GLuint texture))gpa("glIsTexture");
	qglLightModelf = (void (APIENTRY *)(GLenum pname, GLfloat param))gpa("glLightModelf");
	qglLightModelfv = (void (APIENTRY *)(GLenum pname, const GLfloat *params))gpa("glLightModelfv");
	qglLightModeli = (void (APIENTRY *)(GLenum pname, GLint param))gpa("glLightModeli");
	qglLightModeliv = (void (APIENTRY *)(GLenum pname, const GLint *params))gpa("glLightModeliv");
	qglLightf = (void (APIENTRY *)(GLenum light, GLenum pname, GLfloat param))gpa("glLightf");
	qglLightfv = (void (APIENTRY *)(GLenum light, GLenum pname, const GLfloat *params))gpa("glLightfv");
	qglLighti = (void (APIENTRY *)(GLenum light, GLenum pname, GLint param))gpa("glLighti");
	qglLightiv = (void (APIENTRY *)(GLenum light, GLenum pname, const GLint *params))gpa("glLightiv");
	qglLineStipple = (void (APIENTRY *)(GLint factor, GLushort pattern))gpa("glLineStipple");
	qglLineWidth = (void (APIENTRY *)(GLfloat width))gpa("glLineWidth");
	qglListBase = (void (APIENTRY *)(GLuint base))gpa("glListBase");
	qglLoadIdentity = (void (APIENTRY *)(void))gpa("glLoadIdentity");
	qglLoadMatrixd = (void (APIENTRY *)(const GLdouble *m))gpa("glLoadMatrixd");
	qglLoadMatrixf = (void (APIENTRY *)(const GLfloat *m))gpa("glLoadMatrixf");
	qglLoadName = (void (APIENTRY *)(GLuint name))gpa("glLoadName");
	qglLogicOp = (void (APIENTRY *)(GLenum opcode))gpa("glLogicOp");
	qglMap1d = (void (APIENTRY *)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points))gpa("glMap1d");
	qglMap1f = (void (APIENTRY *)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points))gpa("glMap1f");
	qglMap2d = (void (APIENTRY *)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points))gpa("glMap2d");
	qglMap2f = (void (APIENTRY *)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points))gpa("glMap2f");
	qglMapGrid1d = (void (APIENTRY *)(GLint un, GLdouble u1, GLdouble u2))gpa("glMapGrid1d");
	qglMapGrid1f = (void (APIENTRY *)(GLint un, GLfloat u1, GLfloat u2))gpa("glMapGrid1f");
	qglMapGrid2d = (void (APIENTRY *)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2))gpa("glMapGrid2d");
	qglMapGrid2f = (void (APIENTRY *)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2))gpa("glMapGrid2f");
	qglMaterialf = (void (APIENTRY *)(GLenum face, GLenum pname, GLfloat param))gpa("glMaterialf");
	qglMaterialfv = (void (APIENTRY *)(GLenum face, GLenum pname, const GLfloat *params))gpa("glMaterialfv");
	qglMateriali = (void (APIENTRY *)(GLenum face, GLenum pname, GLint param))gpa("glMateriali");
	qglMaterialiv = (void (APIENTRY *)(GLenum face, GLenum pname, const GLint *params))gpa("glMaterialiv");
	qglMatrixMode = (void (APIENTRY *)(GLenum mode))gpa("glMatrixMode");
	qglMultMatrixd = (void (APIENTRY *)(const GLdouble *m))gpa("glMultMatrixd");
	qglMultMatrixf = (void (APIENTRY *)(const GLfloat *m))gpa("glMultMatrixf");
	qglNewList = (void (APIENTRY *)(GLuint list, GLenum mode))gpa("glNewList");
	qglNormal3b = (void (APIENTRY *)(GLbyte nx, GLbyte ny, GLbyte nz))gpa("glNormal3b");
	qglNormal3bv = (void (APIENTRY *)(const GLbyte *v))gpa("glNormal3bv");
	qglNormal3d = (void (APIENTRY *)(GLdouble nx, GLdouble ny, GLdouble nz))gpa("glNormal3d");
	qglNormal3dv = (void (APIENTRY *)(const GLdouble *v))gpa("glNormal3dv");
	qglNormal3f = (void (APIENTRY *)(GLfloat nx, GLfloat ny, GLfloat nz))gpa("glNormal3f");
	qglNormal3fv = (void (APIENTRY *)(const GLfloat *v))gpa("glNormal3fv");
	qglNormal3i = (void (APIENTRY *)(GLint nx, GLint ny, GLint nz))gpa("glNormal3i");
	qglNormal3iv = (void (APIENTRY *)(const GLint *v))gpa("glNormal3iv");
	qglNormal3s = (void (APIENTRY *)(GLshort nx, GLshort ny, GLshort nz))gpa("glNormal3s");
	qglNormal3sv = (void (APIENTRY *)(const GLshort *v))gpa("glNormal3sv");
	qglNormalPointer = (void (APIENTRY *)(GLenum type, GLsizei stride, const GLvoid *pointer))gpa("glNormalPointer");
	qglOrtho = (void (APIENTRY *)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))gpa("glOrtho");
	qglPassThrough = (void (APIENTRY *)(GLfloat token))gpa("glPassThrough");
	qglPixelMapfv = (void (APIENTRY *)(GLenum map, GLsizei mapsize, const GLfloat *values))gpa("glPixelMapfv");
	qglPixelMapuiv = (void (APIENTRY *)(GLenum map, GLsizei mapsize, const GLuint *values))gpa("glPixelMapuiv");
	qglPixelMapusv = (void (APIENTRY *)(GLenum map, GLsizei mapsize, const GLushort *values))gpa("glPixelMapusv");
	qglPixelStoref = (void (APIENTRY *)(GLenum pname, GLfloat param))gpa("glPixelStoref");
	qglPixelStorei = (void (APIENTRY *)(GLenum pname, GLint param))gpa("glPixelStorei");
	qglPixelTransferf = (void (APIENTRY *)(GLenum pname, GLfloat param))gpa("glPixelTransferf");
	qglPixelTransferi = (void (APIENTRY *)(GLenum pname, GLint param))gpa("glPixelTransferi");
	qglPixelZoom = (void (APIENTRY *)(GLfloat xfactor, GLfloat yfactor))gpa("glPixelZoom");
	qglPointSize = (void (APIENTRY *)(GLfloat size))gpa("glPointSize");
	qglPolygonMode = (void (APIENTRY *)(GLenum face, GLenum mode))gpa("glPolygonMode");
	qglPolygonOffset = (void (APIENTRY *)(GLfloat factor, GLfloat units))gpa("glPolygonOffset");
	qglPolygonStipple = (void (APIENTRY *)(const GLubyte *mask))gpa("glPolygonStipple");
	qglPopAttrib = (void (APIENTRY *)(void))gpa("glPopAttrib");
	qglPopClientAttrib = (void (APIENTRY *)(void))gpa("glPopClientAttrib");
	qglPopMatrix = (void (APIENTRY *)(void))gpa("glPopMatrix");
	qglPopName = (void (APIENTRY *)(void))gpa("glPopName");
	qglPrioritizeTextures = (void (APIENTRY *)(GLsizei n, const GLuint *textures, const GLclampf *priorities))gpa("glPrioritizeTextures");
	qglPushAttrib = (void (APIENTRY *)(GLbitfield mask))gpa("glPushAttrib");
	qglPushClientAttrib = (void (APIENTRY *)(GLbitfield mask))gpa("glPushClientAttrib");
	qglPushMatrix = (void (APIENTRY *)(void))gpa("glPushMatrix");
	qglPushName = (void (APIENTRY *)(GLuint name))gpa("glPushName");
	qglRasterPos2d = (void (APIENTRY *)(GLdouble x, GLdouble y))gpa("glRasterPos2d");
	qglRasterPos2dv = (void (APIENTRY *)(const GLdouble *v))gpa("glRasterPos2dv");
	qglRasterPos2f = (void (APIENTRY *)(GLfloat x, GLfloat y))gpa("glRasterPos2f");
	qglRasterPos2fv = (void (APIENTRY *)(const GLfloat *v))gpa("glRasterPos2fv");
	qglRasterPos2i = (void (APIENTRY *)(GLint x, GLint y))gpa("glRasterPos2i");
	qglRasterPos2iv = (void (APIENTRY *)(const GLint *v))gpa("glRasterPos2iv");
	qglRasterPos2s = (void (APIENTRY *)(GLshort x, GLshort y))gpa("glRasterPos2s");
	qglRasterPos2sv = (void (APIENTRY *)(const GLshort *v))gpa("glRasterPos2sv");
	qglRasterPos3d = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z))gpa("glRasterPos3d");
	qglRasterPos3dv = (void (APIENTRY *)(const GLdouble *v))gpa("glRasterPos3dv");
	qglRasterPos3f = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z))gpa("glRasterPos3f");
	qglRasterPos3fv = (void (APIENTRY *)(const GLfloat *v))gpa("glRasterPos3fv");
	qglRasterPos3i = (void (APIENTRY *)(GLint x, GLint y, GLint z))gpa("glRasterPos3i");
	qglRasterPos3iv = (void (APIENTRY *)(const GLint *v))gpa("glRasterPos3iv");
	qglRasterPos3s = (void (APIENTRY *)(GLshort x, GLshort y, GLshort z))gpa("glRasterPos3s");
	qglRasterPos3sv = (void (APIENTRY *)(const GLshort *v))gpa("glRasterPos3sv");
	qglRasterPos4d = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z, GLdouble w))gpa("glRasterPos4d");
	qglRasterPos4dv = (void (APIENTRY *)(const GLdouble *v))gpa("glRasterPos4dv");
	qglRasterPos4f = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z, GLfloat w))gpa("glRasterPos4f");
	qglRasterPos4fv = (void (APIENTRY *)(const GLfloat *v))gpa("glRasterPos4fv");
	qglRasterPos4i = (void (APIENTRY *)(GLint x, GLint y, GLint z, GLint w))gpa("glRasterPos4i");
	qglRasterPos4iv = (void (APIENTRY *)(const GLint *v))gpa("glRasterPos4iv");
	qglRasterPos4s = (void (APIENTRY *)(GLshort x, GLshort y, GLshort z, GLshort w))gpa("glRasterPos4s");
	qglRasterPos4sv = (void (APIENTRY *)(const GLshort *v))gpa("glRasterPos4sv");
	qglReadBuffer = (void (APIENTRY *)(GLenum mode))gpa("glReadBuffer");
	qglReadPixels = (void (APIENTRY *)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels))gpa("glReadPixels");
	qglRectd = (void (APIENTRY *)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2))gpa("glRectd");
	qglRectdv = (void (APIENTRY *)(const GLdouble *v1, const GLdouble *v2))gpa("glRectdv");
	qglRectf = (void (APIENTRY *)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2))gpa("glRectf");
	qglRectfv = (void (APIENTRY *)(const GLfloat *v1, const GLfloat *v2))gpa("glRectfv");
	qglRecti = (void (APIENTRY *)(GLint x1, GLint y1, GLint x2, GLint y2))gpa("glRecti");
	qglRectiv = (void (APIENTRY *)(const GLint *v1, const GLint *v2))gpa("glRectiv");
	qglRects = (void (APIENTRY *)(GLshort x1, GLshort y1, GLshort x2, GLshort y2))gpa("glRects");
	qglRectsv = (void (APIENTRY *)(const GLshort *v1, const GLshort *v2))gpa("glRectsv");
	qglRenderMode = (GLint (APIENTRY *)(GLenum mode))gpa("glRenderMode");
	qglRotated = (void (APIENTRY *)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z))gpa("glRotated");
	qglRotatef = (void (APIENTRY *)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z))gpa("glRotatef");
	qglScaled = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z))gpa("glScaled");
	qglScalef = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z))gpa("glScalef");
	qglScissor = (void (APIENTRY *)(GLint x, GLint y, GLsizei width, GLsizei height))gpa("glScissor");
	qglSelectBuffer = (void (APIENTRY *)(GLsizei size, GLuint *buffer))gpa("glSelectBuffer");
	qglShadeModel = (void (APIENTRY *)(GLenum mode))gpa("glShadeModel");
	qglStencilFunc = (void (APIENTRY *)(GLenum func, GLint ref, GLuint mask))gpa("glStencilFunc");
	qglStencilMask = (void (APIENTRY *)(GLuint mask))gpa("glStencilMask");
	qglStencilOp = (void (APIENTRY *)(GLenum fail, GLenum zfail, GLenum zpass))gpa("glStencilOp");
	qglTexCoord1d = (void (APIENTRY *)(GLdouble s))gpa("glTexCoord1d");
	qglTexCoord1dv = (void (APIENTRY *)(const GLdouble *v))gpa("glTexCoord1dv");
	qglTexCoord1f = (void (APIENTRY *)(GLfloat s))gpa("glTexCoord1f");
	qglTexCoord1fv = (void (APIENTRY *)(const GLfloat *v))gpa("glTexCoord1fv");
	qglTexCoord1i = (void (APIENTRY *)(GLint s))gpa("glTexCoord1i");
	qglTexCoord1iv = (void (APIENTRY *)(const GLint *v))gpa("glTexCoord1iv");
	qglTexCoord1s = (void (APIENTRY *)(GLshort s))gpa("glTexCoord1s");
	qglTexCoord1sv = (void (APIENTRY *)(const GLshort *v))gpa("glTexCoord1sv");
	qglTexCoord2d = (void (APIENTRY *)(GLdouble s, GLdouble t))gpa("glTexCoord2d");
	qglTexCoord2dv = (void (APIENTRY *)(const GLdouble *v))gpa("glTexCoord2dv");
	qglTexCoord2f = (void (APIENTRY *)(GLfloat s, GLfloat t))gpa("glTexCoord2f");
	qglTexCoord2fv = (void (APIENTRY *)(const GLfloat *v))gpa("glTexCoord2fv");
	qglTexCoord2i = (void (APIENTRY *)(GLint s, GLint t))gpa("glTexCoord2i");
	qglTexCoord2iv = (void (APIENTRY *)(const GLint *v))gpa("glTexCoord2iv");
	qglTexCoord2s = (void (APIENTRY *)(GLshort s, GLshort t))gpa("glTexCoord2s");
	qglTexCoord2sv = (void (APIENTRY *)(const GLshort *v))gpa("glTexCoord2sv");
	qglTexCoord3d = (void (APIENTRY *)(GLdouble s, GLdouble t, GLdouble r))gpa("glTexCoord3d");
	qglTexCoord3dv = (void (APIENTRY *)(const GLdouble *v))gpa("glTexCoord3dv");
	qglTexCoord3f = (void (APIENTRY *)(GLfloat s, GLfloat t, GLfloat r))gpa("glTexCoord3f");
	qglTexCoord3fv = (void (APIENTRY *)(const GLfloat *v))gpa("glTexCoord3fv");
	qglTexCoord3i = (void (APIENTRY *)(GLint s, GLint t, GLint r))gpa("glTexCoord3i");
	qglTexCoord3iv = (void (APIENTRY *)(const GLint *v))gpa("glTexCoord3iv");
	qglTexCoord3s = (void (APIENTRY *)(GLshort s, GLshort t, GLshort r))gpa("glTexCoord3s");
	qglTexCoord3sv = (void (APIENTRY *)(const GLshort *v))gpa("glTexCoord3sv");
	qglTexCoord4d = (void (APIENTRY *)(GLdouble s, GLdouble t, GLdouble r, GLdouble q))gpa("glTexCoord4d");
	qglTexCoord4dv = (void (APIENTRY *)(const GLdouble *v))gpa("glTexCoord4dv");
	qglTexCoord4f = (void (APIENTRY *)(GLfloat s, GLfloat t, GLfloat r, GLfloat q))gpa("glTexCoord4f");
	qglTexCoord4fv = (void (APIENTRY *)(const GLfloat *v))gpa("glTexCoord4fv");
	qglTexCoord4i = (void (APIENTRY *)(GLint s, GLint t, GLint r, GLint q))gpa("glTexCoord4i");
	qglTexCoord4iv = (void (APIENTRY *)(const GLint *v))gpa("glTexCoord4iv");
	qglTexCoord4s = (void (APIENTRY *)(GLshort s, GLshort t, GLshort r, GLshort q))gpa("glTexCoord4s");
	qglTexCoord4sv = (void (APIENTRY *)(const GLshort *v))gpa("glTexCoord4sv");
	qglTexCoordPointer = (void (APIENTRY *)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))gpa("glTexCoordPointer");
	qglTexEnvf = (void (APIENTRY *)(GLenum target, GLenum pname, GLfloat param))gpa("glTexEnvf");
	qglTexEnvfv = (void (APIENTRY *)(GLenum target, GLenum pname, const GLfloat *params))gpa("glTexEnvfv");
	qglTexEnvi = (void (APIENTRY *)(GLenum target, GLenum pname, GLint param))gpa("glTexEnvi");
	qglTexEnviv = (void (APIENTRY *)(GLenum target, GLenum pname, const GLint *params))gpa("glTexEnviv");
	qglTexGend = (void (APIENTRY *)(GLenum coord, GLenum pname, GLdouble param))gpa("glTexGend");
	qglTexGendv = (void (APIENTRY *)(GLenum coord, GLenum pname, const GLdouble *params))gpa("glTexGendv");
	qglTexGenf = (void (APIENTRY *)(GLenum coord, GLenum pname, GLfloat param))gpa("glTexGenf");
	qglTexGenfv = (void (APIENTRY *)(GLenum coord, GLenum pname, const GLfloat *params))gpa("glTexGenfv");
	qglTexGeni = (void (APIENTRY *)(GLenum coord, GLenum pname, GLint param))gpa("glTexGeni");
	qglTexGeniv = (void (APIENTRY *)(GLenum coord, GLenum pname, const GLint *params))gpa("glTexGeniv");
	qglTexImage1D = (void (APIENTRY *)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels))gpa("glTexImage1D");
	qglTexImage2D = (void (APIENTRY *)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels))gpa("glTexImage2D");
	qglTexParameterf = (void (APIENTRY *)(GLenum target, GLenum pname, GLfloat param))gpa("glTexParameterf");
	qglTexParameterfv = (void (APIENTRY *)(GLenum target, GLenum pname, const GLfloat *params))gpa("glTexParameterfv");
	qglTexParameteri = (void (APIENTRY *)(GLenum target, GLenum pname, GLint param))gpa("glTexParameteri");
	qglTexParameteriv = (void (APIENTRY *)(GLenum target, GLenum pname, const GLint *params))gpa("glTexParameteriv");
	qglTexSubImage1D = (void (APIENTRY *)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels))gpa("glTexSubImage1D");
	qglTexSubImage2D = (void (APIENTRY *)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))gpa("glTexSubImage2D");
	qglTranslated = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z))gpa("glTranslated");
	qglTranslatef = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z))gpa("glTranslatef");
	qglVertex2d = (void (APIENTRY *)(GLdouble x, GLdouble y))gpa("glVertex2d");
	qglVertex2dv = (void (APIENTRY *)(const GLdouble *v))gpa("glVertex2dv");
	qglVertex2f = (void (APIENTRY *)(GLfloat x, GLfloat y))gpa("glVertex2f");
	qglVertex2fv = (void (APIENTRY *)(const GLfloat *v))gpa("glVertex2fv");
	qglVertex2i = (void (APIENTRY *)(GLint x, GLint y))gpa("glVertex2i");
	qglVertex2iv = (void (APIENTRY *)(const GLint *v))gpa("glVertex2iv");
	qglVertex2s = (void (APIENTRY *)(GLshort x, GLshort y))gpa("glVertex2s");
	qglVertex2sv = (void (APIENTRY *)(const GLshort *v))gpa("glVertex2sv");
	qglVertex3d = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z))gpa("glVertex3d");
	qglVertex3dv = (void (APIENTRY *)(const GLdouble *v))gpa("glVertex3dv");
	qglVertex3f = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z))gpa("glVertex3f");
	qglVertex3fv = (void (APIENTRY *)(const GLfloat *v))gpa("glVertex3fv");
	qglVertex3i = (void (APIENTRY *)(GLint x, GLint y, GLint z))gpa("glVertex3i");
	qglVertex3iv = (void (APIENTRY *)(const GLint *v))gpa("glVertex3iv");
	qglVertex3s = (void (APIENTRY *)(GLshort x, GLshort y, GLshort z))gpa("glVertex3s");
	qglVertex3sv = (void (APIENTRY *)(const GLshort *v))gpa("glVertex3sv");
	qglVertex4d = (void (APIENTRY *)(GLdouble x, GLdouble y, GLdouble z, GLdouble w))gpa("glVertex4d");
	qglVertex4dv = (void (APIENTRY *)(const GLdouble *v))gpa("glVertex4dv");
	qglVertex4f = (void (APIENTRY *)(GLfloat x, GLfloat y, GLfloat z, GLfloat w))gpa("glVertex4f");
	qglVertex4fv = (void (APIENTRY *)(const GLfloat *v))gpa("glVertex4fv");
	qglVertex4i = (void (APIENTRY *)(GLint x, GLint y, GLint z, GLint w))gpa("glVertex4i");
	qglVertex4iv = (void (APIENTRY *)(const GLint *v))gpa("glVertex4iv");
	qglVertex4s = (void (APIENTRY *)(GLshort x, GLshort y, GLshort z, GLshort w))gpa("glVertex4s");
	qglVertex4sv = (void (APIENTRY *)(const GLshort *v))gpa("glVertex4sv");
	qglVertexPointer = (void (APIENTRY *)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))gpa("glVertexPointer");
	qglViewport = (void (APIENTRY *)(GLint x, GLint y, GLsizei width, GLsizei height))gpa("glViewport");

	/* Extension pointers stay NULL on macOS. The OpenGL framework exports
	 * these symbols, but the Metal-backed legacy implementation rejects
	 * their legacy enums (GL_SHARED_TEXTURE_PALETTE_EXT palette uploads,
	 * GL_EXT point parameters, GL_SGIS_multitexture texture units),
	 * raising GL_INVALID_ENUM. The renderer null-checks every one of them
	 * and falls back to its GL 1.1 paths, matching the original Linux
	 * build where they were never resolved either. */

	/* GL 1.1 essentials must exist or the renderer cannot run */
	if (!qglBegin || !qglEnd || !qglBindTexture || !qglTexImage2D ||
		!qglDrawArrays || !qglEnable || !qglDisable || !qglViewport ||
		!qglMatrixMode || !qglLoadIdentity || !qglClearColor || !qglClear ||
		!qglGetError || !qglGetString)
		return false;

	return true;
}

void QGL_Shutdown(void)
{
	qglAccum = NULL;
	qglAlphaFunc = NULL;
	qglAreTexturesResident = NULL;
	qglArrayElement = NULL;
	qglBegin = NULL;
	qglBindTexture = NULL;
	qglBitmap = NULL;
	qglBlendFunc = NULL;
	qglCallList = NULL;
	qglCallLists = NULL;
	qglClear = NULL;
	qglClearAccum = NULL;
	qglClearColor = NULL;
	qglClearDepth = NULL;
	qglClearIndex = NULL;
	qglClearStencil = NULL;
	qglClipPlane = NULL;
	qglColor3b = NULL;
	qglColor3bv = NULL;
	qglColor3d = NULL;
	qglColor3dv = NULL;
	qglColor3f = NULL;
	qglColor3fv = NULL;
	qglColor3i = NULL;
	qglColor3iv = NULL;
	qglColor3s = NULL;
	qglColor3sv = NULL;
	qglColor3ub = NULL;
	qglColor3ubv = NULL;
	qglColor3ui = NULL;
	qglColor3uiv = NULL;
	qglColor3us = NULL;
	qglColor3usv = NULL;
	qglColor4b = NULL;
	qglColor4bv = NULL;
	qglColor4d = NULL;
	qglColor4dv = NULL;
	qglColor4f = NULL;
	qglColor4fv = NULL;
	qglColor4i = NULL;
	qglColor4iv = NULL;
	qglColor4s = NULL;
	qglColor4sv = NULL;
	qglColor4ub = NULL;
	qglColor4ubv = NULL;
	qglColor4ui = NULL;
	qglColor4uiv = NULL;
	qglColor4us = NULL;
	qglColor4usv = NULL;
	qglColorMask = NULL;
	qglColorMaterial = NULL;
	qglColorPointer = NULL;
	qglCopyPixels = NULL;
	qglCopyTexImage1D = NULL;
	qglCopyTexImage2D = NULL;
	qglCopyTexSubImage1D = NULL;
	qglCopyTexSubImage2D = NULL;
	qglCullFace = NULL;
	qglDeleteLists = NULL;
	qglDeleteTextures = NULL;
	qglDepthFunc = NULL;
	qglDepthMask = NULL;
	qglDepthRange = NULL;
	qglDisable = NULL;
	qglDisableClientState = NULL;
	qglDrawArrays = NULL;
	qglDrawBuffer = NULL;
	qglDrawElements = NULL;
	qglDrawPixels = NULL;
	qglEdgeFlag = NULL;
	qglEdgeFlagPointer = NULL;
	qglEdgeFlagv = NULL;
	qglEnable = NULL;
	qglEnableClientState = NULL;
	qglEnd = NULL;
	qglEndList = NULL;
	qglEvalCoord1d = NULL;
	qglEvalCoord1dv = NULL;
	qglEvalCoord1f = NULL;
	qglEvalCoord1fv = NULL;
	qglEvalCoord2d = NULL;
	qglEvalCoord2dv = NULL;
	qglEvalCoord2f = NULL;
	qglEvalCoord2fv = NULL;
	qglEvalMesh1 = NULL;
	qglEvalMesh2 = NULL;
	qglEvalPoint1 = NULL;
	qglEvalPoint2 = NULL;
	qglFeedbackBuffer = NULL;
	qglFinish = NULL;
	qglFlush = NULL;
	qglFogf = NULL;
	qglFogfv = NULL;
	qglFogi = NULL;
	qglFogiv = NULL;
	qglFrontFace = NULL;
	qglFrustum = NULL;
	qglGenLists = NULL;
	qglGenTextures = NULL;
	qglGetBooleanv = NULL;
	qglGetClipPlane = NULL;
	qglGetDoublev = NULL;
	qglGetError = NULL;
	qglGetFloatv = NULL;
	qglGetIntegerv = NULL;
	qglGetLightfv = NULL;
	qglGetLightiv = NULL;
	qglGetMapdv = NULL;
	qglGetMapfv = NULL;
	qglGetMapiv = NULL;
	qglGetMaterialfv = NULL;
	qglGetMaterialiv = NULL;
	qglGetPixelMapfv = NULL;
	qglGetPixelMapuiv = NULL;
	qglGetPixelMapusv = NULL;
	qglGetPointerv = NULL;
	qglGetPolygonStipple = NULL;
	qglGetString = NULL;
	qglGetTexEnvfv = NULL;
	qglGetTexEnviv = NULL;
	qglGetTexGendv = NULL;
	qglGetTexGenfv = NULL;
	qglGetTexGeniv = NULL;
	qglGetTexImage = NULL;
	qglGetTexLevelParameterfv = NULL;
	qglGetTexLevelParameteriv = NULL;
	qglGetTexParameterfv = NULL;
	qglGetTexParameteriv = NULL;
	qglHint = NULL;
	qglIndexMask = NULL;
	qglIndexPointer = NULL;
	qglIndexd = NULL;
	qglIndexdv = NULL;
	qglIndexf = NULL;
	qglIndexfv = NULL;
	qglIndexi = NULL;
	qglIndexiv = NULL;
	qglIndexs = NULL;
	qglIndexsv = NULL;
	qglIndexub = NULL;
	qglIndexubv = NULL;
	qglInitNames = NULL;
	qglInterleavedArrays = NULL;
	qglIsEnabled = NULL;
	qglIsList = NULL;
	qglIsTexture = NULL;
	qglLightModelf = NULL;
	qglLightModelfv = NULL;
	qglLightModeli = NULL;
	qglLightModeliv = NULL;
	qglLightf = NULL;
	qglLightfv = NULL;
	qglLighti = NULL;
	qglLightiv = NULL;
	qglLineStipple = NULL;
	qglLineWidth = NULL;
	qglListBase = NULL;
	qglLoadIdentity = NULL;
	qglLoadMatrixd = NULL;
	qglLoadMatrixf = NULL;
	qglLoadName = NULL;
	qglLogicOp = NULL;
	qglMap1d = NULL;
	qglMap1f = NULL;
	qglMap2d = NULL;
	qglMap2f = NULL;
	qglMapGrid1d = NULL;
	qglMapGrid1f = NULL;
	qglMapGrid2d = NULL;
	qglMapGrid2f = NULL;
	qglMaterialf = NULL;
	qglMaterialfv = NULL;
	qglMateriali = NULL;
	qglMaterialiv = NULL;
	qglMatrixMode = NULL;
	qglMultMatrixd = NULL;
	qglMultMatrixf = NULL;
	qglNewList = NULL;
	qglNormal3b = NULL;
	qglNormal3bv = NULL;
	qglNormal3d = NULL;
	qglNormal3dv = NULL;
	qglNormal3f = NULL;
	qglNormal3fv = NULL;
	qglNormal3i = NULL;
	qglNormal3iv = NULL;
	qglNormal3s = NULL;
	qglNormal3sv = NULL;
	qglNormalPointer = NULL;
	qglOrtho = NULL;
	qglPassThrough = NULL;
	qglPixelMapfv = NULL;
	qglPixelMapuiv = NULL;
	qglPixelMapusv = NULL;
	qglPixelStoref = NULL;
	qglPixelStorei = NULL;
	qglPixelTransferf = NULL;
	qglPixelTransferi = NULL;
	qglPixelZoom = NULL;
	qglPointSize = NULL;
	qglPolygonMode = NULL;
	qglPolygonOffset = NULL;
	qglPolygonStipple = NULL;
	qglPopAttrib = NULL;
	qglPopClientAttrib = NULL;
	qglPopMatrix = NULL;
	qglPopName = NULL;
	qglPrioritizeTextures = NULL;
	qglPushAttrib = NULL;
	qglPushClientAttrib = NULL;
	qglPushMatrix = NULL;
	qglPushName = NULL;
	qglRasterPos2d = NULL;
	qglRasterPos2dv = NULL;
	qglRasterPos2f = NULL;
	qglRasterPos2fv = NULL;
	qglRasterPos2i = NULL;
	qglRasterPos2iv = NULL;
	qglRasterPos2s = NULL;
	qglRasterPos2sv = NULL;
	qglRasterPos3d = NULL;
	qglRasterPos3dv = NULL;
	qglRasterPos3f = NULL;
	qglRasterPos3fv = NULL;
	qglRasterPos3i = NULL;
	qglRasterPos3iv = NULL;
	qglRasterPos3s = NULL;
	qglRasterPos3sv = NULL;
	qglRasterPos4d = NULL;
	qglRasterPos4dv = NULL;
	qglRasterPos4f = NULL;
	qglRasterPos4fv = NULL;
	qglRasterPos4i = NULL;
	qglRasterPos4iv = NULL;
	qglRasterPos4s = NULL;
	qglRasterPos4sv = NULL;
	qglReadBuffer = NULL;
	qglReadPixels = NULL;
	qglRectd = NULL;
	qglRectdv = NULL;
	qglRectf = NULL;
	qglRectfv = NULL;
	qglRecti = NULL;
	qglRectiv = NULL;
	qglRects = NULL;
	qglRectsv = NULL;
	qglRenderMode = NULL;
	qglRotated = NULL;
	qglRotatef = NULL;
	qglScaled = NULL;
	qglScalef = NULL;
	qglScissor = NULL;
	qglSelectBuffer = NULL;
	qglShadeModel = NULL;
	qglStencilFunc = NULL;
	qglStencilMask = NULL;
	qglStencilOp = NULL;
	qglTexCoord1d = NULL;
	qglTexCoord1dv = NULL;
	qglTexCoord1f = NULL;
	qglTexCoord1fv = NULL;
	qglTexCoord1i = NULL;
	qglTexCoord1iv = NULL;
	qglTexCoord1s = NULL;
	qglTexCoord1sv = NULL;
	qglTexCoord2d = NULL;
	qglTexCoord2dv = NULL;
	qglTexCoord2f = NULL;
	qglTexCoord2fv = NULL;
	qglTexCoord2i = NULL;
	qglTexCoord2iv = NULL;
	qglTexCoord2s = NULL;
	qglTexCoord2sv = NULL;
	qglTexCoord3d = NULL;
	qglTexCoord3dv = NULL;
	qglTexCoord3f = NULL;
	qglTexCoord3fv = NULL;
	qglTexCoord3i = NULL;
	qglTexCoord3iv = NULL;
	qglTexCoord3s = NULL;
	qglTexCoord3sv = NULL;
	qglTexCoord4d = NULL;
	qglTexCoord4dv = NULL;
	qglTexCoord4f = NULL;
	qglTexCoord4fv = NULL;
	qglTexCoord4i = NULL;
	qglTexCoord4iv = NULL;
	qglTexCoord4s = NULL;
	qglTexCoord4sv = NULL;
	qglTexCoordPointer = NULL;
	qglTexEnvf = NULL;
	qglTexEnvfv = NULL;
	qglTexEnvi = NULL;
	qglTexEnviv = NULL;
	qglTexGend = NULL;
	qglTexGendv = NULL;
	qglTexGenf = NULL;
	qglTexGenfv = NULL;
	qglTexGeni = NULL;
	qglTexGeniv = NULL;
	qglTexImage1D = NULL;
	qglTexImage2D = NULL;
	qglTexParameterf = NULL;
	qglTexParameterfv = NULL;
	qglTexParameteri = NULL;
	qglTexParameteriv = NULL;
	qglTexSubImage1D = NULL;
	qglTexSubImage2D = NULL;
	qglTranslated = NULL;
	qglTranslatef = NULL;
	qglVertex2d = NULL;
	qglVertex2dv = NULL;
	qglVertex2f = NULL;
	qglVertex2fv = NULL;
	qglVertex2i = NULL;
	qglVertex2iv = NULL;
	qglVertex2s = NULL;
	qglVertex2sv = NULL;
	qglVertex3d = NULL;
	qglVertex3dv = NULL;
	qglVertex3f = NULL;
	qglVertex3fv = NULL;
	qglVertex3i = NULL;
	qglVertex3iv = NULL;
	qglVertex3s = NULL;
	qglVertex3sv = NULL;
	qglVertex4d = NULL;
	qglVertex4dv = NULL;
	qglVertex4f = NULL;
	qglVertex4fv = NULL;
	qglVertex4i = NULL;
	qglVertex4iv = NULL;
	qglVertex4s = NULL;
	qglVertex4sv = NULL;
	qglVertexPointer = NULL;
	qglViewport = NULL;
	qglLockArraysEXT = NULL;
	qglUnlockArraysEXT = NULL;
	qglPointParameterfEXT = NULL;
	qglPointParameterfvEXT = NULL;
	qglColorTableEXT = NULL;
	qglSelectTextureSGIS = NULL;
	qglMTexCoord2fSGIS = NULL;
}
